/** BUY deal-chain + MatchChat trade chrome (KO canonical + JA pilot overlay). */
export const dealChainKo = {
  dealMissingTitle: "거래 정보를 찾을 수 없어요",
  dealMyTrades: "내 거래",
  dealTradeList: "거래 목록",
  dealNotSubmitted: "미제출",
  dealNone: "없음",
  dealShutterCount: "컷수",
  dealUsageCount: "사용량 / 횟수",
  dealShutterCountValue: "{n}컷",
  dealComponents: "구성품",
  dealAppearance: "외관",
  dealKnownIssues: "기능 이상",
  dealTradeMethod: "거래 방식",
  dealConfirmNeeded: "확인 필요",
  dealConfirmDone: "확인 완료",
  dealWaiting: "대기 중",
  dealMe: "나",
  dealPeer: "상대",
  dealWaitingPeerConfirm: "상대 확인 대기 중",
  dealBackToChat: "채팅으로 돌아가기",
  dealPayCta: "결제하기",
  dealProductLabel: "제품",
  dealPriceLabel: "가격",
  dealImageFileOnly: "이미지 파일만 올릴 수 있어요.",
  dealPhotoTooLarge: "700KB 이하 사진을 사용해 주세요.",
  dealPhotoReadFailed: "사진을 읽지 못했어요.",
  tradeBoth: "둘 다 가능",
  tradeMeetupOrShipping: "직거래 · 택배 모두",

  evidenceTitleSeller: "상품 정보 등록",
  evidenceTitleBuyer: "상품 정보 확인",
  evidenceEyebrow: "상품 정보",
  evidenceTrustTitle: "판매자가 등록한 상품 정보예요",
  evidenceTrustBody:
    "판매자가 직접 등록한 정보예요. DAN은 제출 내용을 기록하지만 상품 상태나 정품 여부를 대신 보증하지 않아요.",
  evidenceConnectFirstTitle: "먼저 구매자와 연결해 주세요",
  evidenceConnectFirstBody:
    "제안이 선택됐다면 먼저 연결해 대화하세요. 실제 거래를 이어갈 때 상품 정보를 등록합니다.",
  evidenceBackToOffers: "판매 제안으로 돌아가기",
  evidenceMissingBody: "거래 목록에서 다시 들어와 주세요.",
  evidenceVerifyTitle: "실거래 전 판매자 검증이 필요해요",
  evidenceVerifyBody:
    "제안은 먼저 보낼 수 있지만 실제 거래를 진행하려면 휴대폰·본인·정산계좌 확인이 필요해요.",
  evidencePhotoRequired: "현재 보유 사진 · 필수",
  evidenceChallengeBody:
    "아래 코드를 종이나 다른 화면에 띄워 실제 물품과 함께 촬영해 주세요. DAN이 진품이나 상태를 보증하는 것은 아니지만, 오래된 도용 사진을 쓰기 어렵게 합니다.",
  evidenceChallengeCode: "촬영 코드",
  evidenceChallengeTtl: "15분 동안 유효",
  evidenceChallengeLoading: "촬영 코드 발급 중…",
  evidenceChallengeFail: "촬영 코드를 발급하지 못했어요.",
  evidenceNewCode: "새 코드 받기",
  evidencePhotoAlt: "현재 보유 물품",
  evidencePhotoWithCode: "물품과 촬영 코드 {code}가 함께 보이게 찍어주세요",
  evidencePhotoWaitCode: "촬영 코드가 발급되면 사진을 추가할 수 있어요",
  evidenceSectionProduct: "제품 정보",
  evidenceSectionProductHint: "사용량·식별번호·구매 및 보증 정보가 있다면 함께 남겨요.",
  evidenceSerialLabel: "시리얼 / 식별번호 끝자리 (선택)",
  evidencePurchaseDate: "구매일",
  evidenceWarrantyEnd: "보증 종료",
  evidenceSectionCondition: "구성품 · 상태 · 추가 정보",
  evidenceSectionConditionHint: "거래 조건에 그대로 기록될 내용이에요.",
  evidenceCosmetic: "외관 상태",
  evidenceCosmeticPh: "예: 상단 미세스크래치 1곳",
  evidenceKnownIssuesLabel: "알려진 기능 이상",
  evidenceKnownIssuesPh: "없다면 ‘없음’이라고 적어주세요",
  evidenceRepair: "수리 이력",
  evidenceRepairPh: "없음 / 수리 내용",
  evidenceWater: "침수 / 물손상 이력 (해당 시)",
  evidenceWaterPh: "없음 / 있음 / 모름",
  evidenceSave: "상품 정보 저장하기",
  evidenceSaveFail: "상품 정보를 저장하지 못했어요. 잠시 후 다시 시도해 주세요.",
  evidenceReviewSnapshot: "거래 조건 확인",
  evidenceIdentLabel: "식별번호",
  evidenceKnownShort: "알려진 이상",
  evidenceSellerPhotoAlt: "판매자가 제출한 현재 보유 물품",
  evidenceUsagePh: "예: 2417",
  evidenceSerialPh: "예: 3812",
  evidenceCompProduct: "제품",
  evidenceCompBoxDust: "박스/더스트백",
  evidenceCompTag: "택",
  evidenceCompWarranty: "보증서/영수증",
  evidenceCompExtra: "추가 구성품",
  evidenceCompBody: "제품/본체",
  evidenceCompParts: "조립 부품",
  evidenceCompManual: "설명서",
  evidenceCompExtraParts: "추가 부품",
  evidenceCompMain: "본품",
  evidenceCompCase: "케이스",
  evidenceCompBonus: "부록",
  evidenceCompPhotocard: "포토카드/특전",
  evidenceCompReceipt: "영수증",
  evidenceCompOrigBox: "원박스",
  evidenceCompLimited: "한정 구성품",
  evidenceCompBox: "박스",
  evidenceCompCharger: "충전기/어댑터",
  evidenceCompCable: "케이블",

  snapshotTitle: "거래 조건 확인",
  snapshotConfirmHeading: "거래 조건을 확인해 주세요",
  snapshotSellerInfo: "판매자 등록 정보",
  snapshotSellerInfoSub: "보증·구성품·수리 이력",
  snapshotProductInfo: "제품 정보",
  snapshotWarranty: "보증기간",
  snapshotSerialLast4: "식별번호 끝자리",
  snapshotRepair: "수리 이력",
  snapshotWater: "침수 / 물손상 이력",
  snapshotMeetupTitle: "직거래 약속",
  snapshotMeetupPlace: "만남 장소",
  snapshotMeetupAt: "약속 시간",
  snapshotMeetupPlaceHint: "이 거래 참여자만 볼 수 있어요.",
  snapshotMeetupPlacePh: "예: 강남역 11번 출구 스타벅스 앞",
  snapshotTbd: "미정",
  snapshotLockTitle: "확인하면 이 조건으로 거래가 확정돼요.",
  snapshotLockBody: "양쪽 확인 후에는 수정할 수 없어요. 다르면 먼저 채팅에서 조율하세요.",
  snapshotLockedTitle: "거래 조건이 확정됐어요",
  snapshotLockedBody: "결제 후 인계할 때 같은 거래 조건을 다시 확인하세요.",
  snapshotNeedAppointment: "직거래 장소와 시간을 입력해야 거래 조건을 확인할 수 있어요.",
  snapshotSaveFail: "거래 조건을 저장하지 못했어요.",
  snapshotNoEvidenceTitle: "상품 정보가 아직 없어요",
  snapshotNoEvidenceBuyer: "판매자가 상품 정보를 등록하면 거래 조건을 확인할 수 있어요.",
  snapshotNoEvidenceSeller: "먼저 상품 상태와 확인 정보를 등록해 주세요.",
  snapshotRegisterEvidence: "상품 정보 등록",
  snapshotClosedTitle: "종료된 거래 기록",
  snapshotClosedBody: "회원탈퇴로 개인 작성 내용과 상품 확인 정보가 삭제됐어요.",
  snapshotClosedStatus: "거래 상태",
  snapshotClosedCompleted: "완료",
  snapshotClosedEnded: "종료",
  snapshotAgreedAmount: "합의 금액",
  snapshotCompletedTrades: "완료된 거래",
  snapshotConfirmCta: "거래 조건 확인",

  paymentTitle: "결제",
  paymentAmountLabel: "결제 금액",
  paymentProductAmount: "상품 금액",
  paymentFee: "수수료",
  paymentTotal: "총 결제 금액",
  paymentMethodTitle: "결제 수단",
  paymentMethodPick: "결제 수단 선택",
  paymentCard: "카드 결제",
  paymentBank: "계좌 이체",
  paymentGateBadge: "결제 준비 중",
  paymentGateTitle: "현재는 실제 결제를 받을 수 없어요.",
  paymentGateBody: "결제 기능이 연결되기 전까지는 거래 조건 확인까지만 진행할 수 있어요.",
  paymentGateReview: "거래 조건 다시 보기",
  paymentWaitBuyerTitle: "구매자 결제를 기다리고 있어요",
  paymentWaitBuyerBody: "구매자의 결제가 확인되면 인계 단계가 열려요.",
  paymentSafetyTitle: "결제 확인 후 인계를 진행해요.",
  paymentSafetyBody: "결제가 확인되기 전에는 물건을 인도받거나 건네지 마세요.",
  paymentConfirming: "결제 확인 중…",
  paymentPayAmount: "{amount} 결제하기",
  paymentAlreadyTitle: "결제가 확인됐어요",
  paymentAlreadyBody: "이제 판매자와 물품 인계 방법을 조율하세요.",
  paymentHandoffCta: "인계 진행",
  paymentNeedLockTitle: "먼저 거래 조건을 확정해 주세요",
  paymentNeedLockBody: "양쪽이 거래 조건을 확인한 뒤 결제할 수 있어요.",
  paymentStatusFail: "결제 상태를 변경하지 못했어요.",
  paymentToMyTrades: "내 거래로",
  paymentReviewTerms: "거래 조건 확인",

  handoffTitle: "거래 진행 중",
  handoffShippingLabel: "배송 · 수령 확인",
  handoffMeetupLabel: "직거래 · 인계 확인",
  handoffNeedLockBody: "양쪽이 같은 거래 조건을 확인해야 인계 단계로 넘어갈 수 있어요.",
  handoffNeedPayTitle: "결제가 먼저 필요해요",
  handoffNeedPayBody: "결제 완료가 서버에서 확인된 뒤 직거래 인계 단계가 열립니다.",
  handoffEyebrow: "인계",
  handoffLead: "확정한 거래 조건과 실제 물건이 같은지 마지막으로 확인해요.",
  handoffProgressAria: "거래 진행 단계",
  handoffProgressTerms: "거래 조건",
  handoffProgressTermsDone: "양쪽 확인 완료",
  handoffProgressPay: "결제",
  handoffPayDone: "결제 완료",
  handoffPayWaiting: "결제 대기 중",
  handoffComplete: "거래 완료",
  handoffCoordinateChat: "채팅에서 인계 방법을 조율하세요",
  handoffAfterPay: "결제 완료 후 진행",
  handoffDisputePausedTitle: "거래가 분쟁 검토 상태예요",
  handoffDisputePausedBody: "분쟁이 해결되기 전에는 거래 완료 처리를 진행하지 않습니다.",
  handoffDoneTitle: "거래가 완료됐어요",
  handoffDoneBody: "양쪽의 확인이 끝났습니다. 완료된 거래는 거래 내역에 기록돼요.",
  handoffViewMyTrades: "내 거래 보기",
  handoffBuyerFinal: "구매자 최종 확인",
  handoffSellerFinal: "판매자 최종 확인",
  handoffBuyerHint: "제품·구성품·상태가 위 조건과 일치할 때만 확인하세요.",
  handoffSellerHint: "구매자가 제품을 확인한 뒤 실제 인도를 완료했을 때 확인하세요.",
  handoffBuyerConfirm: "물품을 확인했습니다",
  handoffSellerConfirm: "제품 인도를 완료했습니다",
  handoffDisputeSummary: "거래 조건과 다르거나 문제가 있나요?",
  handoffDisputePh: "확인한 문제를 구체적으로 적어주세요.",
  handoffDisputeSubmit: "거래 중지하고 분쟁 접수",
  handoffConfirmFail: "최종 확인을 저장하지 못했어요.",
  handoffDisputeFail: "분쟁을 접수하지 못했어요.",
  handoffDisputeOtherRequired: "기타 사유는 내용을 적어주세요.",
  handoffChatCoordinate: "채팅에서 인계 방법 조율",
  disputeWrongItem: "다른 물건이에요",
  disputeSnapshotMismatch: "확정한 거래 조건과 달라요",
  disputeMajorDefect: "고지되지 않은 큰 하자가 있어요",
  disputeNotReceived: "물건을 받지 못했어요",
  disputeOther: "기타",

  chatBackAria: "뒤로가기",
  chatRealtimeLive: "실시간",
  chatRealtimeRecovering: "실시간 연결이 끊겼어요. 메시지는 자동으로 다시 불러옵니다.",
  chatDealProgressAria: "거래 진행 단계",
  chatStepProduct: "상품",
  chatStepTerms: "조건",
  chatStepPay: "결제",
  chatStepHandoff: "인계",
  chatPeerFallback: "상대",
  chatBuyConnectedState: "연결됐어요 · 먼저 대화해 보세요",
  chatBuyConnectedHint: "거래를 계속하기로 했다면 판매자가 상품 상태와 확인 정보를 등록해요.",
  chatRegisterEvidence: "상품 정보 등록",
  chatReviewOffer: "제안 다시 보기",
  chatCancelDeal: "거래 취소",
  chatEvidenceReadyState: "상품 정보가 준비됐어요",
  chatEvidenceReadyHint: "상품 상태와 가격을 확인하고 거래 조건을 확정하세요.",
  chatConfirmTerms: "거래 조건 확인",
  chatViewEvidence: "상품 정보 보기",
  chatPayTurnState: "결제를 진행할 차례예요",
  chatPayTurnHint: "거래 조건은 확정됐어요. 결제가 확인되면 인계 단계로 넘어갑니다.",
  chatPayNow: "결제하기",
  chatViewLockedTerms: "확정된 거래 조건 보기",
  chatHandoffState: "물품 인계 확인 단계예요",
  chatHandoffHint: "실제 물품과 확정한 거래 조건을 다시 확인한 뒤 인계를 완료하세요.",
  chatHandoffConfirm: "인계 확인",
  chatMsgRead: "읽음",
  chatMsgSent: "전송됨",
  chatNewMessages: "새 메시지 {n}개 ↓",
  chatReadonlyCompleted: "거래가 완료되어 채팅이 읽기 전용이에요.",
  chatReadonlyClosed: "종료된 거래 · 채팅은 읽기 전용이에요.",
} as const;

export const dealChainJa: { [K in keyof typeof dealChainKo]: string } = {
  dealMissingTitle: "取引情報が見つかりません",
  dealMyTrades: "自分の取引",
  dealTradeList: "取引一覧",
  dealNotSubmitted: "未提出",
  dealNone: "なし",
  dealShutterCount: "シャッター数",
  dealUsageCount: "使用量 / 回数",
  dealShutterCountValue: "{n}枚",
  dealComponents: "付属品",
  dealAppearance: "外観",
  dealKnownIssues: "機能不具合",
  dealTradeMethod: "受け渡し方法",
  dealConfirmNeeded: "確認が必要",
  dealConfirmDone: "確認済み",
  dealWaiting: "待機中",
  dealMe: "自分",
  dealPeer: "相手",
  dealWaitingPeerConfirm: "相手の確認待ち",
  dealBackToChat: "チャットに戻る",
  dealPayCta: "支払う",
  dealProductLabel: "商品",
  dealPriceLabel: "価格",
  dealImageFileOnly: "画像ファイルのみアップロードできます。",
  dealPhotoTooLarge: "700KB以下の写真を使ってください。",
  dealPhotoReadFailed: "写真を読み込めませんでした。",
  tradeBoth: "どちらも可",
  tradeMeetupOrShipping: "手渡し・配送どちらも",

  evidenceTitleSeller: "商品情報を登録",
  evidenceTitleBuyer: "商品情報を確認",
  evidenceEyebrow: "商品情報",
  evidenceTrustTitle: "販売者が登録した商品情報です",
  evidenceTrustBody:
    "販売者が直接登録した情報です。DANは提出内容を記録しますが、状態や真贋を保証しません。",
  evidenceConnectFirstTitle: "先に購入者とつながってください",
  evidenceConnectFirstBody:
    "提案が選ばれたら、まず接続して会話してください。実際の取引に進むときに商品情報を登録します。",
  evidenceBackToOffers: "販売提案に戻る",
  evidenceMissingBody: "取引一覧からもう一度開いてください。",
  evidenceVerifyTitle: "実取引の前に販売者確認が必要です",
  evidenceVerifyBody:
    "提案は先に送れますが、実際の取引には電話・本人・振込口座の確認が必要です。",
  evidencePhotoRequired: "現物写真 · 必須",
  evidenceChallengeBody:
    "下のコードを紙や別画面に出して、実際の商品と一緒に撮影してください。DANが真贋や状態を保証するわけではありませんが、古い流用写真を使いにくくします。",
  evidenceChallengeCode: "撮影コード",
  evidenceChallengeTtl: "15分間有効",
  evidenceChallengeLoading: "撮影コードを発行中…",
  evidenceChallengeFail: "撮影コードを発行できませんでした。",
  evidenceNewCode: "新しいコードを取得",
  evidencePhotoAlt: "現物写真",
  evidencePhotoWithCode: "商品と撮影コード {code} が写るように撮ってください",
  evidencePhotoWaitCode: "撮影コードが発行されると写真を追加できます",
  evidenceSectionProduct: "商品詳細",
  evidenceSectionProductHint: "使用量・識別番号・購入日・保証があれば一緒に残してください。",
  evidenceSerialLabel: "シリアル / 識別番号の末尾（任意）",
  evidencePurchaseDate: "購入日",
  evidenceWarrantyEnd: "保証終了",
  evidenceSectionCondition: "付属品 · 状態 · 追加情報",
  evidenceSectionConditionHint: "取引条件にそのまま記録される内容です。",
  evidenceCosmetic: "外観の状態",
  evidenceCosmeticPh: "例：上面に薄い傷が1か所",
  evidenceKnownIssuesLabel: "既知の機能不具合",
  evidenceKnownIssuesPh: "なければ「なし」と書いてください",
  evidenceRepair: "修理履歴",
  evidenceRepairPh: "なし / 修理内容",
  evidenceWater: "浸水・水濡れ履歴（該当時）",
  evidenceWaterPh: "なし / あり / 不明",
  evidenceSave: "商品情報を保存",
  evidenceSaveFail: "商品情報を保存できませんでした。しばらくしてから再試行してください。",
  evidenceReviewSnapshot: "取引条件を確認",
  evidenceIdentLabel: "識別番号",
  evidenceKnownShort: "既知の不具合",
  evidenceSellerPhotoAlt: "販売者が提出した現物写真",
  evidenceUsagePh: "例：2417",
  evidenceSerialPh: "例：3812",
  evidenceCompProduct: "本体",
  evidenceCompBoxDust: "箱/ダストバッグ",
  evidenceCompTag: "タグ",
  evidenceCompWarranty: "保証書/レシート",
  evidenceCompExtra: "追加付属品",
  evidenceCompBody: "本体",
  evidenceCompParts: "組み立て部品",
  evidenceCompManual: "説明書",
  evidenceCompExtraParts: "追加部品",
  evidenceCompMain: "本体",
  evidenceCompCase: "ケース",
  evidenceCompBonus: "付録",
  evidenceCompPhotocard: "特典/フォトカード",
  evidenceCompReceipt: "レシート",
  evidenceCompOrigBox: "外箱",
  evidenceCompLimited: "限定付属品",
  evidenceCompBox: "箱",
  evidenceCompCharger: "充電器/アダプター",
  evidenceCompCable: "ケーブル",

  snapshotTitle: "取引条件の確認",
  snapshotConfirmHeading: "取引条件を確認してください",
  snapshotSellerInfo: "販売者登録情報",
  snapshotSellerInfoSub: "保証・付属品・修理履歴",
  snapshotProductInfo: "商品情報",
  snapshotWarranty: "保証期間",
  snapshotSerialLast4: "識別番号の末尾",
  snapshotRepair: "修理履歴",
  snapshotWater: "浸水・水濡れ履歴",
  snapshotMeetupTitle: "手渡しの約束",
  snapshotMeetupPlace: "待ち合わせ場所",
  snapshotMeetupAt: "約束の時間",
  snapshotMeetupPlaceHint: "この取引の参加者だけが見られます。",
  snapshotMeetupPlacePh: "例：渋谷駅ハチ公前",
  snapshotTbd: "未定",
  snapshotLockTitle: "確認するとこの条件で取引が確定します。",
  snapshotLockBody: "双方確認後は修正できません。違う場合は先にチャットで調整してください。",
  snapshotLockedTitle: "取引条件が確定しました",
  snapshotLockedBody: "支払い後の受け渡しでも同じ取引条件を再確認してください。",
  snapshotNeedAppointment: "手渡しの場所と時間を入力しないと条件を確認できません。",
  snapshotSaveFail: "取引条件を保存できませんでした。",
  snapshotNoEvidenceTitle: "まだ商品情報がありません",
  snapshotNoEvidenceBuyer: "販売者が商品情報を登録すると取引条件を確認できます。",
  snapshotNoEvidenceSeller: "先に商品の状態と確認情報を登録してください。",
  snapshotRegisterEvidence: "商品情報を登録",
  snapshotClosedTitle: "終了した取引記録",
  snapshotClosedBody: "退会により個人の記入内容と商品確認情報が削除されました。",
  snapshotClosedStatus: "取引状態",
  snapshotClosedCompleted: "完了",
  snapshotClosedEnded: "終了",
  snapshotAgreedAmount: "合意金額",
  snapshotCompletedTrades: "完了した取引",
  snapshotConfirmCta: "取引条件を確認",

  paymentTitle: "支払い",
  paymentAmountLabel: "支払い金額",
  paymentProductAmount: "商品金額",
  paymentFee: "手数料",
  paymentTotal: "合計金額",
  paymentMethodTitle: "支払い方法",
  paymentMethodPick: "支払い方法を選択",
  paymentCard: "カード払い",
  paymentBank: "銀行振込",
  paymentGateBadge: "支払い準備中",
  paymentGateTitle: "現在は実際の支払いを受け付けていません。",
  paymentGateBody: "支払い機能が接続されるまでは、取引条件の確認まで進めます。",
  paymentGateReview: "取引条件を見直す",
  paymentWaitBuyerTitle: "購入者の支払いを待っています",
  paymentWaitBuyerBody: "購入者の支払いが確認されると受け渡し段階が開きます。",
  paymentSafetyTitle: "支払い確認後に受け渡しを進めます。",
  paymentSafetyBody: "支払いが確認される前に物を渡したり受け取ったりしないでください。",
  paymentConfirming: "支払い確認中…",
  paymentPayAmount: "{amount} を支払う",
  paymentAlreadyTitle: "支払いが確認されました",
  paymentAlreadyBody: "販売者と受け渡し方法を調整してください。",
  paymentHandoffCta: "受け渡しへ",
  paymentNeedLockTitle: "先に取引条件を確定してください",
  paymentNeedLockBody: "双方が取引条件を確認してから支払えます。",
  paymentStatusFail: "支払い状態を変更できませんでした。",
  paymentToMyTrades: "自分の取引へ",
  paymentReviewTerms: "取引条件を確認",

  handoffTitle: "取引進行中",
  handoffShippingLabel: "配送 · 受取確認",
  handoffMeetupLabel: "手渡し · 受け渡し確認",
  handoffNeedLockBody: "双方が同じ取引条件を確認しないと受け渡し段階に進めません。",
  handoffNeedPayTitle: "先に支払いが必要です",
  handoffNeedPayBody: "サーバーで支払い完了が確認されたあと、手渡しの受け渡し段階が開きます。",
  handoffEyebrow: "受け渡し",
  handoffLead: "確定した取引条件と実際の商品が同じか、最後に確認します。",
  handoffProgressAria: "取引の進行段階",
  handoffProgressTerms: "取引条件",
  handoffProgressTermsDone: "双方確認済み",
  handoffProgressPay: "支払い",
  handoffPayDone: "支払い完了",
  handoffPayWaiting: "支払い待ち",
  handoffComplete: "取引完了",
  handoffCoordinateChat: "チャットで受け渡し方法を調整してください",
  handoffAfterPay: "支払い完了後に進行",
  handoffDisputePausedTitle: "取引は紛争審査中です",
  handoffDisputePausedBody: "紛争が解決するまで取引完了には進めません。",
  handoffDoneTitle: "取引が完了しました",
  handoffDoneBody: "双方の確認が終わりました。完了した取引は履歴に残ります。",
  handoffViewMyTrades: "自分の取引を見る",
  handoffBuyerFinal: "購入者の最終確認",
  handoffSellerFinal: "販売者の最終確認",
  handoffBuyerHint: "商品・付属品・状態が上記条件と一致するときだけ確認してください。",
  handoffSellerHint: "購入者が商品を確認し、実際の引き渡しが終わったときに確認してください。",
  handoffBuyerConfirm: "商品を確認しました",
  handoffSellerConfirm: "商品の引き渡しを完了しました",
  handoffDisputeSummary: "取引条件と違う、または問題がありますか？",
  handoffDisputePh: "確認した問題を具体的に書いてください。",
  handoffDisputeSubmit: "取引を止め、紛争を申請",
  handoffConfirmFail: "最終確認を保存できませんでした。",
  handoffDisputeFail: "紛争を受け付けできませんでした。",
  handoffDisputeOtherRequired: "その他の理由では内容を書いてください。",
  handoffChatCoordinate: "チャットで受け渡し方法を調整",
  disputeWrongItem: "別の商品です",
  disputeSnapshotMismatch: "確定した取引条件と違います",
  disputeMajorDefect: "告知されていない大きな不具合があります",
  disputeNotReceived: "商品を受け取っていません",
  disputeOther: "その他",

  chatBackAria: "戻る",
  chatRealtimeLive: "リアルタイム",
  chatRealtimeRecovering: "リアルタイム接続が切れました。メッセージは自動で再取得します。",
  chatDealProgressAria: "取引の進行段階",
  chatStepProduct: "商品",
  chatStepTerms: "条件",
  chatStepPay: "支払い",
  chatStepHandoff: "受け渡し",
  chatPeerFallback: "相手",
  chatBuyConnectedState: "つながりました · まず会話してみましょう",
  chatBuyConnectedHint: "取引を続けるなら、販売者が商品状態と確認情報を登録します。",
  chatRegisterEvidence: "商品情報を登録",
  chatReviewOffer: "提案を見直す",
  chatCancelDeal: "取引をやめる",
  chatEvidenceReadyState: "商品情報が準備できました",
  chatEvidenceReadyHint: "商品状態と価格を確認し、取引条件を確定してください。",
  chatConfirmTerms: "取引条件を確認",
  chatViewEvidence: "商品情報を見る",
  chatPayTurnState: "支払いの番です",
  chatPayTurnHint: "取引条件は確定しました。支払いが確認されると受け渡し段階へ進みます。",
  chatPayNow: "支払う",
  chatViewLockedTerms: "確定した取引条件を見る",
  chatHandoffState: "受け渡し確認の段階です",
  chatHandoffHint: "実際の商品と確定した取引条件を再確認してから受け渡しを完了してください。",
  chatHandoffConfirm: "受け渡しを確認",
  chatMsgRead: "既読",
  chatMsgSent: "送信済み",
  chatNewMessages: "新しいメッセージ {n}件 ↓",
  chatReadonlyCompleted: "取引が完了したため、チャットは読み取り専用です。",
  chatReadonlyClosed: "終了した取引 · チャットは読み取り専用です。",
};

export type DealChainCopyKey = keyof typeof dealChainKo;

export function fillCopyTemplate(
  template: string,
  vars: Record<string, string | number>,
): string {
  return template.replace(/\{(\w+)\}/g, (_m, name: string) => String(vars[name] ?? ""));
}
