export const ko = {
  "brandTag": "찾는 사람이 먼저",
  "navCreate": "찾는 물건",
  "navFeed": "수요 둘러보기",
  "navMy": "My DAN",
  "logout": "로그아웃",
  "login": "로그인",
  "navHome": "홈",
  "navDemand": "수요",
  "heroTitle": "찾는 사람이 먼저 올리는 마켓",
  "heroBody1": "판매글을 기다리지 마세요.",
  "heroBody2": "원하는 가격을 남기면 보유자가 수요를 확인합니다.",
  "ctaCreate": "찾는 물건 등록",
  "ctaBrowse": "지금 사람들이 찾는 물건",
  "featuredTitle": "지금 많이 찾고 있어요",
  "featuredDesc": "실제 구매 희망이 먼저 모입니다.",
  "viewAllDemand": "전체 수요 보기",
  "seekingSuffix": "명이 찾는 중",
  "priceHope": "희망 가격",
  "recent7d": "최근 7일",
  "highestIntent": "최고 구매 의향",
  "viewDemand": "수요 보기",
  "feedTitle": "사람들이 지금 찾는 물건",
  "feedDesc": "판매자가 아니라, 찾는 사람 수가 먼저 보입니다.",
  "searchPh": "제품명, 브랜드 검색",
  "all": "전체",
  "camera": "카메라",
  "lens": "렌즈",
  "electronics": "전자기기",
  "sealed": "미개봉",
  "likeNew": "거의 새것",
  "lightlyUsed": "사용감 적음",
  "any": "상관없음",
  "meetup": "직거래",
  "shipping": "택배",
  "won": "원",
  "manWon": "만원",
  "myung": "명",
  "noChange": "변동 없음",
  "seoul": "서울",
  "gyeonggi": "경기",
  "busan": "부산",
  "daegu": "대구",
  "incheon": "인천",
  "mina": "민아",
  "jun": "준호",
  "hae": "해린",
  "you": "나",
  "seongdong": "서울 성동구",
  "mapo": "서울 마포구",
  "haeundae": "부산 해운대구",
  "gangnam": "서울 강남구",
  "next": "다음",
  "prev": "이전",
  "createTitle": "찾는 물건 등록",
  "createDesc": "제품과 최대 희망가만 있어도 됩니다.",
  "step1": "1. 제품 선택",
  "step2": "2. 원하는 조건",
  "step3": "3. 거래 조건",
  "step4": "4. 확인",
  "product": "제품",
  "condition": "상태",
  "maxPrice": "희망 가격 (최대)",
  "maxPriceHint": "이 금액 이하라면 구매하고 싶어요.",
  "location": "지역",
  "tradeMethod": "거래 방식",
  "submitDemand": "수요 등록",
  "quotePrefix": "이하라면 구매하고 싶어요",
  "haveIt": "가지고 있어요",
  "haveItTitle": "이 물건을 가지고 있나요?",
  "haveItBody": "아직 팔 생각이 없어도 괜찮아요. 내 물건으로 등록하면 이 제품의 수요를 계속 확인할 수 있어요.",
  "ownershipNote": "Ownership 은 판매글이 아닙니다.",
  "registerOwned": "내 물건으로 등록",
  "sellIntent": "판매 의향",
  "sellCta": "이 가격이면 팔 수도 있어요",
  "myDan": "My DAN",
  "matchLead": "조건이 맞는 상대가 있어요.",
  "sendInterest": "거래 의사 보내기",
  "connect": "연결하기",
  "noSearch": "검색 결과가 없어요",
  "priceDist": "희망 가격 분포",
  "seekingDetailSuffix": "명이 이 제품을 찾고 있어요",
  "ownTitle": "보유 등록",
  "ownDone": "내 물건으로 등록했어요",
  "sellTitle": "판매 의향",
  "sellDesc": "얼마라면 판매를 생각해볼 수 있나요?",
  "minPriceLabel": "이 가격 이상이면 판매 고려",
  "currentHighest": "현재 최고 구매 희망가",
  "resetDemo": "데모 데이터 초기화",
  "quickStart": "빠른 시작",
  "tabOverview": "요약",
  "tabDemands": "찾는 물건",
  "tabOwned": "보유",
  "tabSelling": "판매 고려",
  "tabMatches": "매칭",
  "statDemands": "찾는 물건",
  "statOwned": "보유한 물건",
  "statSelling": "판매 고려 중",
  "statMatches": "새로운 매칭",
  "demoLogin": "데모 로그인",
  "needLogin": "로그인이 필요해요",
  "matchStatusPotential": "조건 일치",
  "matchStatusInterested": "구매자 관심",
  "matchStatusAccepted": "판매자 수락",
  "matchStatusConnected": "연결됨",
  "matchStatusDeclined": "거절됨",
  "matchStatusClosed": "종료",
  "sellConsiderPrice": "판매 고려 가격",
  "buyerExists": "구매 희망자",
  "exists": "있음",
  "hopePrice": "희망 가격",
  "waitingSeller": "판매자 응답 대기 중",
  "connectedMsg": "연결되었습니다. 채팅은 곧 열릴 예정이에요.",
  "noMatch": "아직 매칭이 없어요",
  "leaveSellIntent": "판매 의향 남기기",
  "viewInMy": "내 DAN에서 보기",
  "reviewDemand": "수요 다시 보기",
  "goBack": "돌아가기",
  "check": "확인하기",
  "seekersLabel": "찾는 사람",
  "ownDoneCountMid": "이 제품을 찾는 사람이",
  "ownDoneCountEnd": " 있어요.",
  "ownDoneBody": "판매글을 공개한 게 아닙니다.",
  "sellNotListing": "지금 바로 판매글을 올리는 단계가 아닙니다.",
  "matchHint": "수요와 판매 의향 가격이 맞으면 여기에 매칭이 생깁니다.",
  "noDemands": "찾는 물건이 있나요?",
  "noOwned": "가지고 있는 물건을 등록하면",
  "noSell": "판매 의향이 없어요",
  "viewMatches": "매칭 보기",
  "missingDemand": "수요 정보를 찾을 수 없어요",
  "missingProduct": "제품을 찾을 수 없어요",
  "missingOwn": "보유 정보를 찾을 수 없어요",
  "alreadyOwnedPrefix": "이미 내 물건으로 등록되어 있어요.",
  "below": " 이하 · ",
  "above": " 이상이면 고려 · ",
  "newMatchesPrefix": "새로운 매칭 ",
  "newMatchesSuffix": "건이 있습니다.",
  "avgHope": "평균 희망가",
  "topHope": "최고 희망가",
  "registerSame": "같은 제품 수요 등록하기",
  "buyerSide": "찾는 쪽이신가요? ",
  "noSearchBody": "다른 키워드로 찾아보거나, 찾는 물건을 직접 등록해 보세요.",
  "noMatchBody": "수요를 등록하거나, 보유한 물건에 판매 의향을 남기면 매칭이 나타납니다.",
  "needLoginBody": "내 수요와 보유, 매칭을 보려면 데모 계정으로 들어가 주세요.",
  "locationPh": "예: 서울 성동구",
  "unentered": "미입력",
  "statusColon": "상태: ",
  "locationColon": "지역: ",
  "tradeColon": "거래: ",
  "myDescSuffix": "님의 수요 · 보유 · 판매 의향 · 매칭",
  "ownDesc": "Ownership != Listing. 가격 없이 보유 사실만 남깁니다.",
  "noOwnedBody": "누가 찾고 있는가 확인할 수 있어요.",
  "noSellBody": "보유 등록 후 판매 의향을 남기면 됩니다.",
  "missingOwnBody": "먼저 물건을 보유 등록한 뒤 판매 의향을 남겨 주세요.",
  "minPriceHint": "조건이 맞는 수요와 자동으로 Match됩니다.",
  "relatedMatchesMid": "이 제품과 관련된 매칭이 ",
  "relatedMatchesEnd": "건 있습니다.",
  "detailMissingBody": "다른 제품을 둘러보거나 찾는 물건을 등록해 보세요.",
  "highestHopeShort": "최고 희망가",
  "thisWeek": "이번 주",
  "seekingOnly": "찾는 중",
  "buyUntil": "구매 희망",
  "sellFrom": "판매 희망",
  "untilSuffix": "까지",
  "fromSuffix": "부터",
  "matchReady": "조건이 맞는 사람이 생겼어요",
  "myHope": "내 희망가",
  "marketHigh": "현재 최고 수요",
  "optionalDetails": "추가 조건 (선택)",
  "stepEssentials": "1. 제품 + 희망가",
  "stepOptional": "2. 조건 확인",
  "sellPrompt": "얼마라면 판매를 생각해볼 수 있나요?",
  "sellSentenceEnd": "원 이상이면 판매를 생각해볼 수 있어요.",
  "iWould": "나는",
  "noDemandsBody": "원하는 가격을 먼저 남겨보세요.",
  "ownAhaHigh": "가장 높은 구매 희망가는",
  "bandSuffix": "만원대"
} as const;
