export const ko = {
  "brandTag": "찾는 사람이 먼저",
  "navCreate": "요청 올리기",
  "navCreateShort": "요청",
  "navFeed": "수요 보기",
  "navMy": "My DAN",
  "displayName": "이름",
  "demandFirstLead": "필요한 사람이 먼저 남긴 요청이에요.",
  "respondToThisNeed": "이 필요에 응답하기",
  "ownerResponsesLead": "이 요청에 도착한 응답",
  "chatWith": "님과 대화",
  "logout": "로그아웃",
  "login": "로그인",
  "navHome": "홈",
  "navDemand": "수요",
  "composerTitle": "뭐가 필요하세요?",
  "composerPlaceholder": "사고 싶거나, 빌리거나, 누군가에게 부탁할 일을 적어보세요",
  "composerHint": "필요한 사람이 먼저 올립니다.",
  "typeBuy": "물건 구매",
  "typeBorrow": "빌리기",
  "typeTask": "심부름",
  "typeService": "서비스",
  "feedNowTitle": "지금 올라온 수요",
  "feedNowDesc": "구매·대여·심부름·서비스가 함께 보입니다.",
  "ctaCreate": "요청 올리기",
  "ctaBrowse": "수요 둘러보기",
  "featuredTitle": "지금 올라온 수요",
  "featuredDesc": "필요한 사람이 먼저 남긴 요청입니다.",
  "viewAllDemand": "전체 수요 보기",
  "seekingSuffix": "명이 찾는 중",
  "similarSeeking": "명이 비슷하게 찾는 중",
  "priceHope": "희망 가격",
  "recent7d": "최근 7일",
  "highestIntent": "최고 희망가",
  "viewDemand": "자세히",
  "feedTitle": "수요 피드",
  "feedDesc": "판매글이 아니라, 필요한 사람의 요청이 먼저입니다.",
  "searchPh": "제목, 지역, 키워드",
  "all": "전체",
  "camera": "카메라",
  "lens": "렌즈",
  "electronics": "전자기기",
  "furniture": "가구",
  "camping": "캠핑",
  "other": "기타",
  "errand": "심부름",
  "serviceCat": "서비스",
  "rental": "대여",
  "sealed": "미개봉",
  "likeNew": "거의 새것",
  "lightlyUsed": "사용감 적음",
  "any": "상관없음",
  "meetup": "직거래",
  "shipping": "택배",
  "won": "원",
  "manWon": "만원",
  "myung": "명",
  "noChange": "변동 없음",
  "seoul": "서울",
  "gyeonggi": "경기",
  "busan": "부산",
  "daegu": "대구",
  "incheon": "인천",
  "mina": "민아",
  "jun": "준호",
  "hae": "해린",
  "you": "나",
  "seongdong": "서울 성동구",
  "mapo": "서울 마포구",
  "haeundae": "부산 해운대구",
  "gangnam": "서울 강남구",
  "pyeongtaek": "평택",
  "next": "다음",
  "prev": "이전",
  "createTitle": "요청 올리기",
  "createDesc": "유형만 고르면 필요한 입력만 보여요.",
  "whatNeeded": "무엇이 필요하세요?",
  "stepEssentials": "기본 정보",
  "stepOptional": "선택 사항",
  "optionalDetails": "나중에 수정해도 됩니다.",
  "product": "제품",
  "condition": "상태",
  "maxPrice": "희망 가격 (최대)",
  "maxPriceHint": "이 금액 이하라면 구매하고 싶어요.",
  "location": "지역",
  "tradeMethod": "거래 방식",
  "submitDemand": "요청 등록",
  "quotePrefix": "이하라면 구매하고 싶어요",
  "titleLabel": "요청 제목",
  "descLabel": "자세히",
  "budgetLabel": "예산 / 보상",
  "borrowBudgetTotal": "대여 총 예산",
  "borrowBudgetHint": "기간 전체에 대한 예산이에요. 하루 단가가 아닙니다.",
  "itemName": "물건",
  "period": "기간",
  "borrowStart": "빌리는 시작",
  "borrowEnd": "반납 예정",
  "dueAt": "마감 시간",
  "preferredAt": "희망 시간",
  "whenNeeded": "언제 필요하세요?",
  "pickDemandType": "먼저 요청 유형을 골라 주세요.",
  "timePastError": "과거 시간은 선택할 수 없어요.",
  "borrowRangeError": "반납 예정은 빌리는 시작보다 뒤여야 해요.",
  "timeRequiredError": "시간을 입력해 주세요.",
  "reward": "보상",
  "productSearch": "찾는 제품",
  "productSearchPh": "제품 이름 검색",
  "productCustom": "목록에 없어요 · 직접 입력",
  "productCustomPh": "필요한 제품 이름",
  "productSelected": "선택됨",
  "myBuyManage": "내 구매 요청 관리",
  "haveIt": "가지고 있어요",
  "haveItTitle": "이 물건을 가지고 있나요?",
  "haveItBody": "아직 팔 생각이 없어도 괜찮아요. 내 물건으로 등록하면 이 제품의 수요를 계속 확인할 수 있어요.",
  "ownershipNote": "Ownership 은 판매글이 아닙니다.",
  "registerOwned": "내 물건으로 등록",
  "sellIntent": "판매 의향",
  "sellCta": "이 가격이면 팔 수도 있어요",
  "myDan": "My DAN",
  "matchLead": "조건이 맞는 상대가 있어요.",
  "sendInterest": "거래 의사 보내기",
  "connect": "연결하기",
  "noSearch": "검색 결과가 없어요",
  "noSearchBody": "다른 키워드나 유형으로 찾아보세요.",
  "seekingOnly": "찾는 중",
  "highestHopeShort": "최고가",
  "thisWeek": "이번 주",
  "bandSuffix": "만원대",
  "needLogin": "로그인이 필요해요",
  "needLoginBody": "데모에서는 바로 로그인할 수 있어요.",
  "demoLogin": "데모 로그인",
  "matchStatusPotential": "조건 일치",
  "matchStatusInterested": "관심 표시됨",
  "matchStatusAccepted": "수락됨",
  "matchStatusConnected": "연결됨",
  "matchStatusDeclined": "거절됨",
  "matchStatusClosed": "종료",
  "buyUntil": "구매 희망",
  "sellFrom": "판매 희망",
  "untilSuffix": "까지",
  "fromSuffix": "부터",
  "waitingSeller": "상대 응답 대기",
  "connectedMsg": "연결되었습니다. My DAN에서 확인하세요.",
  "noMatch": "아직 매칭이 없어요",
  "noMatchBody": "요청을 올리거나 응답하면 여기에 나타나요.",
  "matchReady": "조건이 맞는 상대가 있어요",
  "matchHint": "관심을 보내면 상대가 연결을 확인할 수 있어요.",
  "viewMatches": "매칭 보기",
  "newMatchesPrefix": "새 신호 ",
  "newMatchesSuffix": "건",
  "tabOverview": "한눈에",
  "tabDemands": "내 요청",
  "tabOwned": "내 물건",
  "tabSelling": "판매 의향",
  "tabMatches": "매칭",
  "tabResponses": "내가 응답한 요청",
  "statDemands": "내 요청",
  "statOwned": "내 물건",
  "statSelling": "판매 의향",
  "statMatches": "매칭",
  "myDescSuffix": " 님의 DAN 상태",
  "resetDemo": "데모 초기화",
  "missingProduct": "제품을 찾을 수 없어요",
  "goBack": "돌아가기",
  "missingOwn": "등록된 물건이 없어요",
  "missingOwnBody": "먼저 내 물건을 등록해 주세요.",
  "sellTitle": "판매 의향 남기기",
  "sellPrompt": "이 가격이면 팔 수도 있어요.",
  "sellNotListing": "판매글이 아니라 의향만 남깁니다.",
  "currentHighest": "현재 최고 희망가",
  "seekersLabel": "찾는 사람",
  "iWould": "이 정도면",
  "sellSentenceEnd": "에 팔 수 있어요",
  "minPriceLabel": "최소 희망가",
  "relatedMatchesMid": "관련 매칭 ",
  "relatedMatchesEnd": "건이 있어요",
  "buyerExists": "구매 희망자가 있어요",
  "hopePrice": "희망가",
  "sellConsiderPrice": "판매 희망가",
  "ownTitle": "내 물건 등록",
  "ownDesc": "팔지 않아도 수요를 볼 수 있어요.",
  "ownDoneBody": "등록됐어요. 원하면 판매 의향을 남겨보세요.",
  "ownAhaHigh": "최고 희망가",
  "reviewDemand": "수요 다시 보기",
  "locationPh": "예: 서울 성동구",
  "seekingDetailSuffix": "명이 찾는 중",
  "maxBudget": "최대",
  "perDay": "/일",
  "today": "오늘",
  "respondCta": "제가 할게요",
  "respondBorrow": "빌려드릴 수 있어요",
  "respondService": "이 조건이면 가능합니다",
  "respondSent": "응답을 보냈어요",
  "acceptResponse": "연결하기",
  "attentionTitle": "지금 확인할 것",
  "myRequests": "내가 올린 요청",
  "myResponses": "내가 응답한 요청",
  "myConnections": "연결 / 매칭",
  "myItems": "내가 가진 물건",
  "signalMatch": "조건이 맞는 상대가 있어요",
  "signalOwned": "내 물건을 찾는 사람이 있어요",
  "signalResponse": "응답한 요청이 연결을 기다리고 있어요",
  "emptyFeed": "아직 수요가 없어요",
  "emptyFeedBody": "첫 요청을 올려보세요.",
  "detailBudget": "예산",
  "detailWhen": "시간",
  "detailWhere": "수행 방식",
  "fulfillRemote": "온라인",
  "fulfillShipping": "택배 가능",
  "fulfillShippingShort": "전국 택배",
  "fulfillMeetup": "직거래",
  "fulfillMeetupDemand": "직거래 수요 있음",
  "fulfillOnsite": "현장",
  "fulfillPickup": "픽업",
  "fulfillHow": "어떻게 충족할까요?",
  "buyShippingOpt": "택배 가능",
  "buyMeetupOpt": "직거래",
  "buyMeetupWhere": "어디에서 거래할까요?",
  "borrowWhere": "어디에서 받을까요?",
  "taskModeOnsite": "한 장소에서 하는 일",
  "taskModePickup": "어디서 받아오기",
  "taskModeRoute": "어디서 → 어디로",
  "taskModeRemote": "온라인으로 가능",
  "taskPlace": "어디서 할까요?",
  "taskPickupPlace": "어디서 받아올까요?",
  "taskRouteFrom": "어디서",
  "taskRouteTo": "어디로",
  "serviceOnsite": "직접 와주세요",
  "serviceRemote": "온라인으로 가능",
  "servicePlace": "어디서 할까요?",
  "filterNearby": "내 주변",
  "filterOnline": "온라인",
  "placePh": "예: 평택역 근처",
  "routeArrow": "→",
  "defaultAreaHint": "프로필 기본 지역(입력 기본값용)",
  "viewInMy": "내 DAN에서 보기",
  "missingDemand": "요청을 찾을 수 없어요",
  "heroTitle": "찾는 사람이 먼저 올리는 마켓",
  "heroBody1": "판매글을 기다리지 마세요.",
  "heroBody2": "원하는 가격을 남기면 보유자가 수요를 확인합니다.",
  "detailMissingBody": "요청을 찾을 수 없어요.",
  "avgHope": "평균 희망가",
  "priceDist": "희망가 분포",
  "alreadyOwnedPrefix": "이미 내 물건으로 등록되어 있어요.",
  "leaveSellIntent": "판매 의향 남기기",
  "buyerSide": "같은 물건을 찾고 있나요? ",
  "registerSame": "나도 등록",
  "typeChip": "type-chip",
  "navActivity": "알림",
  "respondSheetTitle": "응답하기",
  "offerPrice": "제안 금액",
  "offerPriceOptional": "선택",
  "availability": "가능한 시간/조건",
  "availabilityPh": "예: 오늘 19:30 이후",
  "responseMessage": "메시지",
  "responseMessagePh": "어떻게 도와드릴 수 있는지 짧게 적어주세요",
  "sendResponse": "응답 보내기",
  "editResponse": "응답 수정",
  "withdrawResponse": "응답 철회",
  "declineResponse": "거절",
  "acceptResponseAction": "수락",
  "responsesTitle": "응답",
  "responseCountSuffix": "개",
  "editDemand": "수정",
  "closeDemand": "요청 마감",
  "closeDemandConfirm": "이 요청을 마감할까요? 새 응답을 받지 않아요.",
  "saveDemand": "저장",
  "demandClosed": "마감된 요청",
  "statusOpen": "대기 중",
  "statusAccepted": "수락됨",
  "statusDeclined": "거절됨",
  "statusWithdrawn": "철회됨",
  "statusActive": "진행 중",
  "statusClosed": "마감",
  "statusMatched": "연결됨",
  "statusWaiting": "상대 확인 중",
  "statusConnected": "연결됨",
  "statusInterested": "관심 도착",
  "chatTitle": "대화",
  "chatPlaceholder": "메시지 입력",
  "chatSend": "보내기",
  "chatEmpty": "아직 메시지가 없어요. 장소나 시간을 먼저 맞춰보세요.",
  "openChat": "대화하기",
  "activityTitle": "알림",
  "activityEmpty": "새로운 알림이 없어요.",
  "activityNewResponse": "새 응답이 도착했어요",
  "activityAccepted": "응답이 수락됐어요",
  "activityDeclined": "응답이 거절됐어요",
  "activityInterest": "구매 관심을 표시했어요",
  "activityConnected": "연결됐어요",
  "activityMessage": "메시지를 보냈어요",
  "activityClosed": "요청이 마감됐어요",
  "markAllRead": "모두 읽음",
  "profileTitle": "프로필",
  "profileEdit": "프로필 수정",
  "profileBio": "소개",
  "profileBioPh": "짧게 소개해 주세요",
  "profileConnections": "연결",
  "profileJoined": "가입",
  "timesSuffix": "회",
  "report": "신고",
  "block": "차단",
  "blockConfirm": "이 사용자를 차단할까요? 더 이상 응답·메시지를 주고받지 않아요.",
  "reportReason": "신고 사유",
  "reportSpam": "스팸",
  "reportFraud": "사기 의심",
  "reportAbuse": "부적절한 행동",
  "reportOther": "기타",
  "reportDetail": "자세한 내용",
  "reportSubmit": "신고하기",
  "reportSent": "신고가 접수됐어요",
  "blockedOk": "차단했어요",
  "myRequestsActive": "진행 중",
  "myRequestsDone": "마감·연결",
  "saving": "저장 중…",
  "retry": "다시 시도",
  "genericError": "잠시 후 다시 시도해 주세요.",
} as const;
