import { useMemo } from "react";
import { dealChainJa } from "@/copy/dealChain";
import { ko } from "@/copy/ko";
import { useDanLocale } from "@/i18n/locale";

/**
 * JP pilot overlays shared copy without changing canonical Korean text or
 * persisting translated strings as domain values. Missing keys stay Korean,
 * and must be audited before enabling Japan storefront availability.
 */
export type LocalizedCopy = { [K in keyof typeof ko]: string };
export const jaPilotCopy: Partial<LocalizedCopy> = {
  ...dealChainJa,
  brandTag: "必要な人から",
  navCreate: "依頼する", navCreateShort: "依頼", navFeed: "探す", navChats: "チャット", navHome: "ホーム",
  displayName: "表示名", logout: "ログアウト", login: "ログイン",
  stepWhat: "何を", stepWhereWhen: "どこで・いつ", stepNext: "次へ", stepPrev: "戻る",
  createTitle: "依頼する", createDesc: "依頼の種類に合わせて必要な情報を入力してください。",
  whatNeeded: "何が必要ですか？", pickDemandType: "まず依頼の種類を選んでください。",
  typeBuy: "買いたい", typeBorrow: "借りたい", typeTask: "おつかい", typeService: "お手伝い",
  all: "すべて", next: "次へ", prev: "戻る",
  productSearch: "探している商品", productSearchPh: "例：iPhone 15 Pro、テント", 
  productSearchHint: "似ている商品があれば候補を表示します。見つからなければ自由入力できます。",
  product: "商品", condition: "商品の状態", maxPrice: "希望価格の上限",
  maxPriceHint: "この金額以下で購入を希望します。", itemName: "借りたい物",
  titleLabel: "タイトル", descLabel: "詳細", serviceTaskLabel: "お願いしたい内容",
  serviceTaskPh: "例：家具の組み立てを手伝ってほしい",
  serviceExtraLabel: "追加情報", serviceExtraPh: "必要な情報だけ記入してください",
  estimatedDuration: "所要時間の目安", estimatedDurationPh: "例：20",
  estimatedDurationHint: "分単位・任意", estimatedDurationUnit: "分",
  detailDuration: "所要時間", detailLocation: "場所", detailWhen: "日時",
  whereNeeded: "どこで必要ですか？", useCurrentLocation: "現在地を使用",
  searchPlace: "場所・地域を検索", enterPlaceManually: "手入力",
  placeAreaLabel: "場所・地域", placeNoteLabel: "場所の補足",
  placeNotePh: "例：駅の近く（任意）", geoLocating: "現在地を確認中…",
  geoDenied: "位置情報が許可されていません。地域名を入力してください。",
  geoFailed: "現在地を取得できませんでした。地域名を入力してください。",
  locationRequiredError: "位置情報を使用するか、地域名を入力してください。",
  typeSwitchConfirm: "依頼の種類を変えると入力内容が消えます。",
  phase2Buy: "どのように受け取りますか？",
  phase2Borrow: "どこで・いつ借りますか？",
  phase2Task: "どこで・いつ必要ですか？",
  phase2Service: "どこで・いつ依頼しますか？",
  budgetLabel: "予算・謝礼", borrowBudgetTotal: "レンタル期間全体の予算",
  borrowBudgetHint: "期間全体の予算です。1日単位ではありません。",
  period: "期間", borrowStart: "借りる日時", borrowEnd: "返却予定",
  dueAt: "期限", preferredAt: "希望日時", datetimePh: "日時を選んでください",
  whenNeeded: "いつ必要ですか？", timePastError: "過去の日時は選べません。",
  borrowRangeError: "返却予定は借りる日時より後にしてください。",
  timeRequiredError: "日時を入力してください。", reward: "謝礼",
  tradeMethod: "受け渡し方法", buyShippingOpt: "配送可", buyMeetupOpt: "手渡し",
  buyMeetupWhere: "どこで受け渡しますか？", borrowWhere: "どこで受け取りますか？",
  fulfillRemote: "オンライン", fulfillShipping: "配送対応", fulfillShippingShort: "配送",
  fulfillMeetup: "手渡し", fulfillMeetupDemand: "手渡し対応",
  fulfillOnsite: "現地対応", fulfillPickup: "引き取り", fulfillHow: "どの方法にしますか？",
  taskHow: "どのように対応しますか？", taskModeOnsite: "その場所で行う",
  taskModePickup: "引き取る", taskModeRoute: "別の場所へ届ける",
  taskModeRemote: "オンライン", taskPlace: "作業場所",
  taskPickupPlace: "引き取り場所", taskRouteFrom: "出発地", taskRouteTo: "目的地",
  serviceOnsite: "訪問してほしい", serviceRemote: "オンラインで可能",
  servicePlace: "サービスを受ける場所", locationPh: "例：福岡市博多区",
  placePh: "例：博多駅周辺", defaultAreaHint: "主に活動する地域",
  routeArrow: "→",
  submitDemand: "依頼を投稿", submitNeedLogin: "ログインして投稿",
  needLogin: "ログインが必要です", needLoginBody: "依頼の投稿や返信にはログインしてください。",
  genericError: "しばらくしてからやり直してください。",
  missingDemand: "依頼が見つかりません", goBack: "戻る",
  whereLabelBuy: "受け渡し方法", whereLabelBorrow: "受け取り方法",
  whereLabelTask: "対応方法", whereLabelService: "実施方法",
  detailBudget: "予算", maxBudget: "上限", statusActive: "募集中",
  statusClosed: "終了", statusMatched: "つながりました", statusExpired: "期限切れ",
  statusOpen: "受付中", statusAccepted: "承認済み", statusDeclined: "お断り済み",
  statusWithdrawn: "取り消し済み", statusWaiting: "相手の確認待ち",
  statusConnected: "接続済み", statusInterested: "関心あり",
  editDemand: "編集", closeDemand: "募集終了",
  closeDemandConfirm: "この依頼の募集を終了しますか？新しい返答は受け付けません。",
  expiredBuyAsk: "まだ探していますか？", extend30d: "7日間延長",
  expiredTimedBody: "依頼は期限を過ぎました。",
  recreateSimilar: "似た依頼を投稿", demandClosed: "募集終了",
  haveIt: "持っています", haveItBody: "この商品をお持ちですか？",
  respondCta: "対応できます", respondBorrow: "お貸しできます",
  respondService: "この条件なら可能です", respondSent: "返答を送信しました",
  respondSheetTitle: "返答する", offerPrice: "提案金額", offerPriceOptional: "任意",
  availability: "対応可能な日時・条件", availabilityShort: "対応可能日時",
  availabilityPh: "例：本日19:30以降",
  responseMessage: "メッセージ",
  responseMessagePh: "どのように対応できるかを簡単に記入してください",
  sendResponse: "返答を送信", editResponse: "返答を編集",
  withdrawResponse: "返答を取り消す", declineResponse: "お断り",
  acceptResponseAction: "承認", openChat: "チャットする",
  ownerResponsesLead: "この依頼への返答", ownerResponsesEmpty: "まだ返答はありません。",
  cancel: "キャンセル", saving: "保存中…", retry: "再試行",
  viewDemand: "詳細を見る",
  chatsTitle: "チャット", chatsEmpty: "まだ会話がありません",
  chatsEmptyBody: "依頼がつながるとここでチャットできます。",
  chatsStartHint: "会話を始めましょう。", chatTitle: "会話", loading: "読み込み中…",
  authHeadline: "必要な人から始まるマーケット",
  loginLead: "ログインしてDANを始めましょう。",
  signupLead: "メールアドレスとパスワードで登録できます。",
  loginToContinue: "続きから依頼を投稿できます。",
  displayNameLabel: "名前", emailLabel: "メールアドレス",
  passwordLabel: "パスワード", createAccount: "登録する",
  haveAccount: "アカウントをお持ちの方はログイン",
  needAccount: "アカウントを作成する",
  authInvalid: "メールアドレスまたはパスワードをご確認ください。",
  authExists: "このメールアドレスは登録されています。",
  authWeakPassword: "パスワードは6文字以上必要です。",
  report: "通報",
  block: "ブロック",
  blockConfirm: "このユーザーをブロックしますか？返答やメッセージのやり取りができなくなります。",
  reportReason: "通報理由",
  reportSpam: "スパム",
  reportFraud: "詐欺の疑い",
  reportAbuse: "不適切な行為",
  reportOther: "その他",
  reportDetail: "詳細",
  reportSubmit: "通報する",
  reportSent: "通報を受け付けました",
  blockedOk: "ブロックしました",
  tradeCompleteCta: "取引完了",
  tradeCancelCta: "取引しないことにしました",
  tradeCancelTitle: "この取引を終了しますか？",
  tradeCancelBody: "チャット履歴は残ります。",
  tradeCancelAction: "取引終了",
  matchStatusCompleted: "取引完了",
  activityMatchCompleted: "取引が完了しました",
  // Trade / match lifecycle (JA chat + My DAN)
  tradeInProgress: "取引進行中",
  tradeInProgressHint: "相手と取引条件を確認してください。",
  tradeConfirmTitle: "実際の取引は終わりましたか？",
  tradeConfirmBuy: "商品の受け渡しは完了しましたか？",
  tradeConfirmBorrow: "返却まですべて終わりましたか？",
  tradeConfirmTask: "お願いした用事は終わりましたか？",
  tradeConfirmService: "サービスの提供は終わりましたか？",
  tradeConfirmAction: "完了を確認",
  tradePeerConfirmed: "相手が取引完了を確認しました。",
  tradePeerConfirmedHint: "取引が終わっていれば確認してください。",
  tradeConfirmPeerCta: "私も完了しました",
  tradeWaitingPeer: "相手の完了確認を待っています。",
  tradeDoneTitle: "取引が完了しました",
  tradeDoneHint: "DANでつながった取引です。",
  tradePeerClosed: "この取引はこれ以上進みません。",
  tradeClosedTitle: "取引が終了しました",
  tradeClosedSeekHint: "まだ探していますか？",
  tradeReopenCta: "もう一度探す",
  tradeReopenBody: "同じ条件で依頼を再開して相手を探します。",
  tradeReopenedToast: "同じ条件で再募集を始めました",
  tradeReopenedHint: "同じ条件で再び探しています。",
  activityMatchTradeClosed: "相手が取引を終了しました",
  matchStatusPotential: "条件一致",
  matchStatusInterested: "関心あり",
  matchStatusAccepted: "承認済み",
  matchStatusConnected: "接続済み",
  matchStatusDeclined: "お断り済み",
  matchStatusClosed: "終了",
  chatWith: "さんと会話",
  chatPlaceholder: "メッセージを入力",
  chatSend: "送信",
  chatEmpty: "まだメッセージはありません。場所や時間から合わせましょう。",
  loadingChat: "読み込み中…",
  // My DAN / nav
  navMy: "My DAN",
  navActivity: "お知らせ",
  navDemand: "探す",
  myDan: "My DAN",
  tabOverview: "一覧",
  tabDemands: "自分の依頼",
  tabOwned: "持ち物",
  tabSelling: "売却意向",
  tabMatches: "マッチ",
  tabResponses: "応じた依頼",
  noMatch: "まだマッチがありません",
  noMatchBody: "依頼を出すか返答するとここに表示されます。",
  matchReady: "条件が合う相手がいます",
  matchHint: "関心を送ると相手が接続を確認できます。",
  viewMatches: "マッチを見る",
  waitingSeller: "相手の返答待ち",
  connectedMsg: "つながりました。My DANで確認してください。",
  // Profile / activity
  profileTitle: "プロフィール",
  profileEdit: "プロフィール編集",
  profileBio: "紹介",
  profileJoined: "登録",
  profileCompleted: "取引完了",
  profileResponded: "返答・接続",
  profileRecent: "最近のDAN活動",
  profileRecentEmpty: "公開できる活動はまだありません。",
  profileArea: "主な活動エリア",
  profileSave: "保存",
  profileActivity: "活動",
  profileMyPosts: "自分の投稿",
  profileMyConnections: "つながり",
  activityTitle: "お知らせ",
  activityEmpty: "新しいお知らせはありません。",
  activityNewResponse: "新しい返答が届きました",
  activityAccepted: "返答が承認されました",
  activityDeclined: "返答がお断りされました",
  activityInterest: "購入の関心が届きました",
  activityConnected: "つながりました",
  activityMessage: "メッセージが届きました",
  activityClosed: "依頼が締め切りになりました",
  activityPeerConnected: "相手が接続を承認しました",
  activityExpiringSoon: "依頼の締め切りが近づいています",
  loadFailed: "読み込めませんでした。",
  dismiss: "閉じる",
  emptyHomeTitle: "まだ依頼がありません",
  emptyHomeBody: "最初の依頼を出すとここに表示されます。",
  // Remaining KO keys (JA pilot UI coverage)
  demandFirstLead: "必要な人が先に残した依頼です。",
  respondToThisNeed: "この依頼に応える",
  stepOf: "/",
  myNow: "今やること",
  myVault: "保管庫",
  connectedPeople: "つながった相手",
  moreActions: "その他",
  composerTitle: "何が必要ですか？",
  composerPlaceholder: "買いたい物、借りたい物、お願いしたいことを書いてください",
  composerHint: "必要な人が先に依頼を残します。",
  feedNowTitle: "今探しています",
  feedNowDesc: "購入・レンタル・おつかい・サービスがまとめて見られます。",
  ctaCreate: "依頼する",
  ctaBrowse: "探す",
  featuredTitle: "今探しています",
  featuredDesc: "必要な人が先に依頼を残します。",
  viewAllDemand: "すべて見る",
  seekingSuffix: "人が探しています",
  similarSeeking: "も似た条件で探しています",
  priceHope: "希望価格",
  recent7d: "直近7日",
  highestIntent: "最高希望価格",
  feedTitle: "今探しています",
  feedDesc: "必要な人が先に依頼を残します。",
  searchPh: "商品・地域・キーワードで探す",
  camera: "カメラ",
  lens: "レンズ",
  electronics: "家電・ガジェット",
  furniture: "家具",
  camping: "キャンプ",
  other: "その他",
  errand: "おつかい",
  serviceCat: "サービス",
  rental: "レンタル",
  sealed: "未開封",
  likeNew: "ほぼ新品",
  lightlyUsed: "使用感少なめ",
  any: "こだわらない",
  meetup: "手渡し",
  shipping: "配送",
  won: "ウォン",
  manWon: "万ウォン",
  myung: "人",
  noChange: "変動なし",
  seoul: "ソウル",
  gyeonggi: "京畿",
  busan: "釜山",
  daegu: "大邱",
  incheon: "仁川",
  mina: "ミナ",
  jun: "ジュンホ",
  hae: "ヘリン",
  you: "自分",
  seongdong: "ソウル 城東区",
  mapo: "ソウル 麻浦区",
  haeundae: "釜山 海雲台区",
  gangnam: "ソウル 江南区",
  pyeongtaek: "平沢",
  stepEssentials: "基本情報",
  stepOptional: "任意項目",
  optionalDetails: "あとから編集できます。",
  location: "地域",
  quotePrefix: "以下なら購入したいです",
  myBuyManage: "購入依頼を管理",
  haveItTitle: "この商品をお持ちですか？",
  ownershipNote: "出品ではありません。持ち物として登録します。",
  priceDistEmpty: "まだ価格データが足りません",
  filterMore: "フィルター",
  suggestPrice: "現在の最高希望価格を提案",
  emptyBio: "まだ紹介がありません。",
  emptyBioSelf: "一言紹介を追加してみましょう。",
  authGoogle: "Googleで登録",
  authEmail: "メールで登録",
  vaultOpen: "保管庫",
  registerOwned: "持ち物として登録",
  sellIntent: "売却意向",
  sellCta: "この価格なら売れるかもしれません",
  matchLead: "条件が合う相手がいます。",
  sendInterest: "取引の意思を送る",
  connect: "接続する",
  noSearch: "検索結果がありません",
  noSearchBody: "別のキーワードや種類で探してみてください。",
  seekingOnly: "募集中",
  highestHopeShort: "最高価格",
  thisWeek: "今週",
  bandSuffix: "万ウォン台",
  demoLogin: "ログイン",
  signup: "新規登録",
  homeCta: "依頼する",
  homeCtaHint: "必要なことを先に残してみましょう。",
  homeQuickHint: "種類を選んですぐ始められます",
  buyUntil: "購入希望",
  sellFrom: "売却希望",
  untilSuffix: "まで",
  fromSuffix: "から",
  newMatchesPrefix: "新しいシグナル ",
  newMatchesSuffix: "件",
  statDemands: "自分の依頼",
  statOwned: "持ち物",
  statSelling: "売却意向",
  statMatches: "マッチ",
  myDescSuffix: " さんのDAN状況",
  resetDemo: "デモをリセット",
  missingProduct: "商品が見つかりません",
  missingOwn: "登録された持ち物がありません",
  missingOwnBody: "先に持ち物を登録してください。",
  sellTitle: "売却意向を残す",
  sellPrompt: "この価格なら売れるかもしれません。",
  sellNotListing: "出品ではなく意向だけ残します。",
  currentHighest: "現在の最高希望価格",
  seekersLabel: "探している人",
  iWould: "このくらいなら",
  sellSentenceEnd: "で売れます",
  minPriceLabel: "最低希望価格",
  relatedMatchesMid: "関連マッチ ",
  relatedMatchesEnd: "件あります",
  buyerExists: "購入希望者がいます",
  hopePrice: "希望価格",
  sellConsiderPrice: "売却希望価格",
  ownTitle: "持ち物を登録",
  ownDesc: "売らなくても関連する依頼を見られます。",
  ownDoneBody: "登録しました。よければ売却意向も残してみてください。",
  ownDoneTitle: "登録しました",
  ownAhaHigh: "最高希望価格",
  priceThoughtBuy: "最大 {price} まで考えています",
  priceThoughtBorrow: "合計 {price} まで使えます",
  priceThoughtReward: "謝礼は {price} くらいです",
  pendingMatches: "確認する取引",
  areaUnset: "活動エリア未設定",
  setAreaForNearby: "近くを使うには活動エリアを設定してください",
  fabCreate: "依頼",
  noAreaNearby: "活動エリアがありません",
  reviewDemand: "依頼を見直す",
  seekingDetailSuffix: "人が探しています",
  perDay: "/日",
  today: "今日",
  acceptResponse: "接続する",
  attentionTitle: "今確認すること",
  myRequests: "自分の依頼",
  myResponses: "応じた依頼",
  emptyMyRequests: "まだ依頼がありません。",
  emptyMyResponses: "まだ応じた依頼がありません。",
  archivedRequests: "保管した依頼",
  emptyArchived: "保管した依頼はありません。",
  seeAll: "すべて見る",
  daysLeft: "残り{n}日",
  expiresToday: "本日締め切り",
  responseCountLabel: "返答 {n}",
  myConnections: "つながり / マッチ",
  myItems: "自分の持ち物",
  signalMatch: "条件が合う相手がいます",
  signalOwned: "持ち物を探している人がいます",
  signalResponse: "応じた依頼が接続待ちです",
  emptyFeed: "まだ依頼がありません",
  emptyFeedBody: "最初の依頼を残してみましょう。",
  detailWhere: "対応方法",
  filterNearby: "近く",
  filterOnline: "オンライン",
  viewInMy: "My DANで見る",
  heroTitle: "必要な人から始まるマーケット",
  heroBody1: "出品を待つ必要はありません。",
  heroBody2: "希望価格を残すと所持者が確認します。",
  detailMissingBody: "依頼が見つかりません。",
  avgHope: "平均希望価格",
  priceDist: "希望価格の分布",
  alreadyOwnedPrefix: "すでに持ち物として登録されています。",
  leaveSellIntent: "売却意向を残す",
  buyerSide: "同じ商品を探していますか？ ",
  registerSame: "自分も登録",
  typeChip: "type-chip",
  responsesTitle: "返答",
  responseCountSuffix: "件",
  saveDemand: "保存",
  expiredSection: "期限切れの依頼",
  expiredOnPrefix: "期限切れ",
  repostDemand: "再投稿",
  viewRequest: "依頼を見る",
  nowEmpty: "今確認する用事はありません。",
  markAllRead: "すべて既読",
  profileBioPh: "短く自己紹介してください",
  profileConnections: "つながり",
  timesSuffix: "回",
  myRequestsActive: "進行中",
  myRequestsDone: "終了・接続済み",
  detailShare: "共有",
  detailShareAria: "依頼を共有",
  detailShareTitle: "{name} · DANの依頼",
  detailShareText: "今 {n}人が {name} を探しています。",
  detailShareOk: "共有しました",
  detailShareCopied: "リンクをコピーしました",
  detailShareManual: "アドレス欄のリンクをコピーしてください",
  detailShareFail: "共有できませんでした",
  detailSeekingEyebrow: "今探している人",
  detailSeekingNow: "が今探しています",
  detailBuyLead: "購入希望者が欲しいものと価格を先に残した依頼です。",
  detailPriceChecking: "価格確認中",
  detailBuyerFulfillment: "購入希望の取引方法",
  detailFulfillmentChecking: "取引方法を確認",
  detailBuyerRequests: "購入依頼",
  detailPeopleSeeking: "この商品を探している人",
  detailCountSuffix: "件",
  detailBuyerDemandN: "購入需要 {n}",
  detailMaxPrefix: "最大",
  detailSendOffer: "提案する",
  detailNoPublicBuyers: "公開中の個別依頼はまだありません。探している人に先に提案できます。",
  detailOfferNowTitle: "希望価格と状態だけ書いてすぐ提案しましょう。",
  detailOfferNowBody: "相手が提案を選ぶと、チャットで商品情報と取引条件を確認します。",
  detailSendOfferCta: "提案を送る",
  detailReuseOwned: "登録済みの持ち物情報を再利用できます。",
  changeDemandType: "依頼の種類を変更",
  createMaxPricePh: "例：800,000",
  createItemNamePh: "例：キャンプ用テント",
  createBorrowBudgetPh: "例：30,000",
  createTaskDescPh: "例：駅で荷物を運んでほしい",
  createTaskBudgetPh: "例：20,000",
  createRewardPh: "例：1,000",
  quickOfferTitle: "販売提案をする",
  quickOfferEyebrow: "販売提案",
  quickOfferSeeking: "今 {n}人が探しています",
  selectedBuyMax: "選んだ購入需要 · 希望上限",
  currentBuyHighest: "現在の最高購入希望価格",
  useThisPrice: "この価格を使う",
  quickOfferPriceLabel: "希望販売価格",
  quickOfferPriceHint: "購入者はまず価格を比べます。",
  quickOfferPricePh: "例：2,130,000",
  myItemCondition: "持ち物の状態",
  possibleTradeMethod: "可能な取引方法",
  extraInfo: "追加情報",
  approxShutter: "おおよそのシャッター数",
  approxShutterHint: "いまはおおよその情報だけで大丈夫です。",
  approxShutterPh: "例：2,400",
  conditionNoteLabel: "状態メモ",
  conditionNotePh: "例：状態良好 · 上部に微細な傷",
  photoLabel: "写真",
  photoOptionalHint: "任意 · なくても提案できます",
  photoHelp: "写真があると相手が判断しやすくなります。",
  quickOfferHelper: "価格・状態・可能な取引方法だけ先に伝えれば大丈夫です。",
  offerSending: "提案中…",
  ownershipCreateFail: "持ち物情報を作成できませんでした。",
  offerSendFail: "販売提案を送れませんでした。",
  sellIntentPriceHint: "購入者がまず価格を確認します。",
  sellIntentShutterHint: "相手が提案を選ぶと詳しい商品情報を確認できます。",
  conditionNoteShort: "状態ひとこと",
  photoOneOptional: "現在の写真1枚",
  photoHelpBuyer: "写真を追加すると購入者が判断しやすくなります",
  offerLightTitle: "まずは気軽に提案しましょう",
  viewBuyDemand: "購入需要を見る",
  offerDetailTitle: "提案の詳細",
  offerMissingTitle: "提案が見つかりません",
  offerMissingBody: "受け取った提案一覧からもう一度確認してください。",
  receivedOffers: "受け取った提案",
  buyerHopeFulfillment: "購入希望の方法",
  sellerCanFulfill: "販売者が可能な方法",
  noSpecialNotes: "特記事項なし",
  sellerLabel: "販売者",
  identityVerified: "本人確認済み",
  completedTradesLabel: "取引完了",
  issueTradesLabel: "問題のある取引",
  viewTradeHistory: "取引履歴を見る",
  selectThisOffer: "この提案を選ぶ",
  processing: "処理中…",
  offerSelectedTitle: "提案を選びました",
  offerSelectedBody: "相手が承認するとチャットが開きます。取引を進めるときに商品情報を確認します。",
  backToReceivedOffers: "受け取った提案に戻る",
  connectedWithSeller: "販売者とつながりました",
  connectedWithSellerBody: "まずチャットで取引の意思を確認してください。商品情報が上がると取引条件を確認できます。",
  startChat: "チャットを始める",
  reviewProductInfo: "商品情報を確認",
  viewCompletedTrade: "完了した取引を見る",
  sellerPhotoAlt: "{name} 販売者が載せた現在の商品",
};
export function useDanCopy(): LocalizedCopy {
  const locale = useDanLocale();
  return useMemo(() => locale === "ja" ? { ...ko, ...jaPilotCopy } : ko, [locale]);
}
