import { useMemo } from "react";
import { ko } from "@/copy/ko";
import { useDanLocale } from "@/i18n/locale";

/**
 * JP pilot overlays shared copy without changing canonical Korean text or
 * persisting translated strings as domain values. Missing keys stay Korean,
 * and must be audited before enabling Japan storefront availability.
 */
export const jaPilotCopy: Partial<typeof ko> = {
  brandTag: "必要な人から",
  navCreate: "依頼する", navCreateShort: "依頼", navFeed: "探す", navChats: "チャット", navHome: "ホーム",
  displayName: "表示名", logout: "ログアウト", login: "ログイン",
  stepWhat: "何を", stepWhereWhen: "どこで・いつ", stepNext: "次へ", stepPrev: "戻る",
  createTitle: "依頼する", createDesc: "依頼の種類に合わせて必要な情報を入力してください。",
  whatNeeded: "何が必要ですか？", pickDemandType: "まず依頼の種類を選んでください。",
  typeBuy: "買いたい", typeBorrow: "借りたい", typeTask: "おつかい", typeService: "お手伝い",
  all: "すべて", next: "次へ", prev: "戻る",
  productSearch: "探している商品", productSearchPh: "例：iPhone 15 Pro、テント", 
  productSearchHint: "似ている商品があれば候補を表示します。見つからなければ自由入力できます。",
  product: "商品", condition: "商品の状態", maxPrice: "希望価格の上限",
  maxPriceHint: "この金額以下で購入を希望します。", itemName: "借りたい物",
  titleLabel: "タイトル", descLabel: "詳細", serviceTaskLabel: "お願いしたい内容",
  serviceTaskPh: "例：家具の組み立てを手伝ってほしい",
  serviceExtraLabel: "追加情報", serviceExtraPh: "必要な情報だけ記入してください",
  estimatedDuration: "所要時間の目安", estimatedDurationPh: "例：20",
  estimatedDurationHint: "分単位・任意", estimatedDurationUnit: "分",
  detailDuration: "所要時間", detailLocation: "場所", detailWhen: "日時",
  whereNeeded: "どこで必要ですか？", useCurrentLocation: "現在地を使用",
  searchPlace: "場所・地域を検索", enterPlaceManually: "手入力",
  placeAreaLabel: "場所・地域", placeNoteLabel: "場所の補足",
  placeNotePh: "例：駅の近く（任意）", geoLocating: "現在地を確認中…",
  geoDenied: "位置情報が許可されていません。地域名を入力してください。",
  geoFailed: "現在地を取得できませんでした。地域名を入力してください。",
  locationRequiredError: "位置情報を使用するか、地域名を入力してください。",
  typeSwitchConfirm: "依頼の種類を変えると入力内容が消えます。",
  phase2Buy: "どのように受け取りますか？",
  phase2Borrow: "どこで・いつ借りますか？",
  phase2Task: "どこで・いつ必要ですか？",
  phase2Service: "どこで・いつ依頼しますか？",
  budgetLabel: "予算・謝礼", borrowBudgetTotal: "レンタル期間全体の予算",
  borrowBudgetHint: "期間全体の予算です。1日単位ではありません。",
  period: "期間", borrowStart: "借りる日時", borrowEnd: "返却予定",
  dueAt: "期限", preferredAt: "希望日時", datetimePh: "日時を選んでください",
  whenNeeded: "いつ必要ですか？", timePastError: "過去の日時は選べません。",
  borrowRangeError: "返却予定は借りる日時より後にしてください。",
  timeRequiredError: "日時を入力してください。", reward: "謝礼",
  tradeMethod: "受け渡し方法", buyShippingOpt: "配送可", buyMeetupOpt: "手渡し",
  buyMeetupWhere: "どこで受け渡しますか？", borrowWhere: "どこで受け取りますか？",
  fulfillRemote: "オンライン", fulfillShipping: "配送対応", fulfillShippingShort: "配送",
  fulfillMeetup: "手渡し", fulfillMeetupDemand: "手渡し対応",
  fulfillOnsite: "現地対応", fulfillPickup: "引き取り", fulfillHow: "どの方法にしますか？",
  taskHow: "どのように対応しますか？", taskModeOnsite: "その場所で行う",
  taskModePickup: "引き取る", taskModeRoute: "別の場所へ届ける",
  taskModeRemote: "オンライン", taskPlace: "作業場所",
  taskPickupPlace: "引き取り場所", taskRouteFrom: "出発地", taskRouteTo: "目的地",
  serviceOnsite: "訪問してほしい", serviceRemote: "オンラインで可能",
  servicePlace: "サービスを受ける場所", locationPh: "例：福岡市博多区",
  placePh: "例：博多駅周辺", defaultAreaHint: "主に活動する地域",
  routeArrow: "→", typeSwitchConfirm: "依頼を切り替えると入力内容は消えます。",
  submitDemand: "依頼を投稿", submitNeedLogin: "ログインして投稿",
  needLogin: "ログインが必要です", needLoginBody: "依頼の投稿や返信にはログインしてください。",
  genericError: "しばらくしてからやり直してください。",
  missingDemand: "依頼が見つかりません", goBack: "戻る",
  whereLabelBuy: "受け渡し方法", whereLabelBorrow: "受け取り方法",
  whereLabelTask: "対応方法", whereLabelService: "実施方法",
  detailBudget: "予算", maxBudget: "上限", statusActive: "募集中",
  statusClosed: "終了", statusMatched: "つながりました", statusExpired: "期限切れ",
  statusOpen: "受付中", statusAccepted: "承認済み", statusDeclined: "お断り済み",
  statusWithdrawn: "取り消し済み", statusWaiting: "相手の確認待ち",
  statusConnected: "接続済み", statusInterested: "関心あり",
  editDemand: "編集", closeDemand: "募集終了",
  closeDemandConfirm: "この依頼の募集を終了しますか？新しい返答は受け付けません。",
  expiredBuyAsk: "まだ探していますか？", extend30d: "7日間延長",
  expiredTimedBody: "依頼は期限を過ぎました。",
  recreateSimilar: "似た依頼を投稿", demandClosed: "募集終了",
  haveIt: "持っています", haveItBody: "この商品をお持ちですか？",
  respondCta: "対応できます", respondBorrow: "お貸しできます",
  respondService: "この条件なら可能です", respondSent: "返答を送信しました",
  respondSheetTitle: "返答する", offerPrice: "提案金額", offerPriceOptional: "任意",
  availability: "対応可能な日時・条件", availabilityShort: "対応可能日時",
  availabilityPh: "例：本日19:30以降",
  responseMessage: "メッセージ",
  responseMessagePh: "どのように対応できるかを簡単に記入してください",
  sendResponse: "返答を送信", editResponse: "返答を編集",
  withdrawResponse: "返答を取り消す", declineResponse: "お断り",
  acceptResponseAction: "承認", openChat: "チャットする",
  ownerResponsesLead: "この依頼への返答", ownerResponsesEmpty: "まだ返答はありません。",
  statusActive: "募集中", cancel: "キャンセル", saving: "保存中…", retry: "再試行",
  offerPriceOptional: "任意", viewDemand: "詳細を見る",
  chatsTitle: "チャット", chatsEmpty: "まだ会話がありません",
  chatsEmptyBody: "依頼がつながるとここでチャットできます。",
  chatsStartHint: "会話を始めましょう。", chatTitle: "会話", loading: "読み込み中…",
  navFeed: "探す",
  authHeadline: "必要な人から始まるマーケット",
  loginLead: "ログインしてDANを始めましょう。",
  signupLead: "メールアドレスとパスワードで登録できます。",
  loginToContinue: "続きから依頼を投稿できます。",
  displayNameLabel: "名前", emailLabel: "メールアドレス",
  passwordLabel: "パスワード", createAccount: "登録する",
  haveAccount: "アカウントをお持ちの方はログイン",
  needAccount: "アカウントを作成する",
  authInvalid: "メールアドレスまたはパスワードをご確認ください。",
  authExists: "このメールアドレスは登録されています。",
  authWeakPassword: "パスワードは6文字以上必要です。",
};
export function useDanCopy(): typeof ko {
  const locale = useDanLocale();
  return useMemo(() => locale === "ja" ? { ...ko, ...jaPilotCopy } : ko, [locale]);
}
