import { useMemo } from "react";
import { ko } from "@/copy/ko";
import { useDanLocale } from "@/i18n/locale";

/**
 * JP pilot overlays shared copy without changing canonical Korean text or
 * persisting translated strings as domain values. Missing keys stay Korean,
 * and must be audited before enabling Japan storefront availability.
 */
export type LocalizedCopy = { [K in keyof typeof ko]: string };
export const jaPilotCopy: Partial<LocalizedCopy> = {
  brandTag: "必要な人から",
  navCreate: "依頼する", navCreateShort: "依頼", navFeed: "探す", navChats: "チャット", navHome: "ホーム",
  displayName: "表示名", logout: "ログアウト", login: "ログイン",
  stepWhat: "何を", stepWhereWhen: "どこで・いつ", stepNext: "次へ", stepPrev: "戻る",
  createTitle: "依頼する", createDesc: "依頼の種類に合わせて必要な情報を入力してください。",
  whatNeeded: "何が必要ですか？", pickDemandType: "まず依頼の種類を選んでください。",
  typeBuy: "買いたい", typeBorrow: "借りたい", typeTask: "おつかい", typeService: "お手伝い",
  all: "すべて", next: "次へ", prev: "戻る",
  productSearch: "探している商品", productSearchPh: "例：iPhone 15 Pro、テント", 
  productSearchHint: "似ている商品があれば候補を表示します。見つからなければ自由入力できます。",
  product: "商品", condition: "商品の状態", maxPrice: "希望価格の上限",
  maxPriceHint: "この金額以下で購入を希望します。", itemName: "借りたい物",
  titleLabel: "タイトル", descLabel: "詳細", serviceTaskLabel: "お願いしたい内容",
  serviceTaskPh: "例：家具の組み立てを手伝ってほしい",
  serviceExtraLabel: "追加情報", serviceExtraPh: "必要な情報だけ記入してください",
  estimatedDuration: "所要時間の目安", estimatedDurationPh: "例：20",
  estimatedDurationHint: "分単位・任意", estimatedDurationUnit: "分",
  detailDuration: "所要時間", detailLocation: "場所", detailWhen: "日時",
  whereNeeded: "どこで必要ですか？", useCurrentLocation: "現在地を使用",
  searchPlace: "場所・地域を検索", enterPlaceManually: "手入力",
  placeAreaLabel: "場所・地域", placeNoteLabel: "場所の補足",
  placeNotePh: "例：駅の近く（任意）", geoLocating: "現在地を確認中…",
  geoDenied: "位置情報が許可されていません。地域名を入力してください。",
  geoFailed: "現在地を取得できませんでした。地域名を入力してください。",
  locationRequiredError: "位置情報を使用するか、地域名を入力してください。",
  typeSwitchConfirm: "依頼の種類を変えると入力内容が消えます。",
  phase2Buy: "どのように受け取りますか？",
  phase2Borrow: "どこで・いつ借りますか？",
  phase2Task: "どこで・いつ必要ですか？",
  phase2Service: "どこで・いつ依頼しますか？",
  budgetLabel: "予算・謝礼", borrowBudgetTotal: "レンタル期間全体の予算",
  borrowBudgetHint: "期間全体の予算です。1日単位ではありません。",
  period: "期間", borrowStart: "借りる日時", borrowEnd: "返却予定",
  dueAt: "期限", preferredAt: "希望日時", datetimePh: "日時を選んでください",
  whenNeeded: "いつ必要ですか？", timePastError: "過去の日時は選べません。",
  borrowRangeError: "返却予定は借りる日時より後にしてください。",
  timeRequiredError: "日時を入力してください。", reward: "謝礼",
  tradeMethod: "受け渡し方法", buyShippingOpt: "配送可", buyMeetupOpt: "手渡し",
  buyMeetupWhere: "どこで受け渡しますか？", borrowWhere: "どこで受け取りますか？",
  fulfillRemote: "オンライン", fulfillShipping: "配送対応", fulfillShippingShort: "配送",
  fulfillMeetup: "手渡し", fulfillMeetupDemand: "手渡し対応",
  fulfillOnsite: "現地対応", fulfillPickup: "引き取り", fulfillHow: "どの方法にしますか？",
  taskHow: "どのように対応しますか？", taskModeOnsite: "その場所で行う",
  taskModePickup: "引き取る", taskModeRoute: "別の場所へ届ける",
  taskModeRemote: "オンライン", taskPlace: "作業場所",
  taskPickupPlace: "引き取り場所", taskRouteFrom: "出発地", taskRouteTo: "目的地",
  serviceOnsite: "訪問してほしい", serviceRemote: "オンラインで可能",
  servicePlace: "サービスを受ける場所", locationPh: "例：福岡市博多区",
  placePh: "例：博多駅周辺", defaultAreaHint: "主に活動する地域",
  routeArrow: "→",
  submitDemand: "依頼を投稿", submitNeedLogin: "ログインして投稿",
  needLogin: "ログインが必要です", needLoginBody: "依頼の投稿や返信にはログインしてください。",
  genericError: "しばらくしてからやり直してください。",
  missingDemand: "依頼が見つかりません", goBack: "戻る",
  whereLabelBuy: "受け渡し方法", whereLabelBorrow: "受け取り方法",
  whereLabelTask: "対応方法", whereLabelService: "実施方法",
  detailBudget: "予算", maxBudget: "上限", statusActive: "募集中",
  statusClosed: "終了", statusMatched: "つながりました", statusExpired: "期限切れ",
  statusOpen: "受付中", statusAccepted: "承認済み", statusDeclined: "お断り済み",
  statusWithdrawn: "取り消し済み", statusWaiting: "相手の確認待ち",
  statusConnected: "接続済み", statusInterested: "関心あり",
  editDemand: "編集", closeDemand: "募集終了",
  closeDemandConfirm: "この依頼の募集を終了しますか？新しい返答は受け付けません。",
  expiredBuyAsk: "まだ探していますか？", extend30d: "7日間延長",
  expiredTimedBody: "依頼は期限を過ぎました。",
  recreateSimilar: "似た依頼を投稿", demandClosed: "募集終了",
  haveIt: "持っています", haveItBody: "この商品をお持ちですか？",
  respondCta: "対応できます", respondBorrow: "お貸しできます",
  respondService: "この条件なら可能です", respondSent: "返答を送信しました",
  respondSheetTitle: "返答する", offerPrice: "提案金額", offerPriceOptional: "任意",
  availability: "対応可能な日時・条件", availabilityShort: "対応可能日時",
  availabilityPh: "例：本日19:30以降",
  responseMessage: "メッセージ",
  responseMessagePh: "どのように対応できるかを簡単に記入してください",
  sendResponse: "返答を送信", editResponse: "返答を編集",
  withdrawResponse: "返答を取り消す", declineResponse: "お断り",
  acceptResponseAction: "承認", openChat: "チャットする",
  ownerResponsesLead: "この依頼への返答", ownerResponsesEmpty: "まだ返答はありません。",
  cancel: "キャンセル", saving: "保存中…", retry: "再試行",
  viewDemand: "詳細を見る",
  chatsTitle: "チャット", chatsEmpty: "まだ会話がありません",
  chatsEmptyBody: "依頼がつながるとここでチャットできます。",
  chatsStartHint: "会話を始めましょう。", chatTitle: "会話", loading: "読み込み中…",
  authHeadline: "必要な人から始まるマーケット",
  loginLead: "ログインしてDANを始めましょう。",
  signupLead: "メールアドレスとパスワードで登録できます。",
  loginToContinue: "続きから依頼を投稿できます。",
  displayNameLabel: "名前", emailLabel: "メールアドレス",
  passwordLabel: "パスワード", createAccount: "登録する",
  haveAccount: "アカウントをお持ちの方はログイン",
  needAccount: "アカウントを作成する",
  authInvalid: "メールアドレスまたはパスワードをご確認ください。",
  authExists: "このメールアドレスは登録されています。",
  authWeakPassword: "パスワードは6文字以上必要です。",
  report: "通報",
  block: "ブロック",
  blockConfirm: "このユーザーをブロックしますか？返答やメッセージのやり取りができなくなります。",
  reportReason: "通報理由",
  reportSpam: "スパム",
  reportFraud: "詐欺の疑い",
  reportAbuse: "不適切な行為",
  reportOther: "その他",
  reportDetail: "詳細",
  reportSubmit: "通報する",
  reportSent: "通報を受け付けました",
  blockedOk: "ブロックしました",
  tradeCompleteCta: "取引完了",
  tradeCancelCta: "取引しないことにしました",
  tradeCancelTitle: "この取引を終了しますか？",
  tradeCancelBody: "チャット履歴は残ります。",
  tradeCancelAction: "取引終了",
  matchStatusCompleted: "取引完了",
  activityMatchCompleted: "取引が完了しました",
  // Trade / match lifecycle (JA chat + My DAN)
  tradeInProgress: "取引進行中",
  tradeInProgressHint: "相手と取引条件を確認してください。",
  tradeConfirmTitle: "実際の取引は終わりましたか？",
  tradeConfirmBuy: "商品の受け渡しは完了しましたか？",
  tradeConfirmBorrow: "返却まですべて終わりましたか？",
  tradeConfirmTask: "お願いした用事は終わりましたか？",
  tradeConfirmService: "サービスの提供は終わりましたか？",
  tradeConfirmAction: "完了を確認",
  tradePeerConfirmed: "相手が取引完了を確認しました。",
  tradePeerConfirmedHint: "取引が終わっていれば確認してください。",
  tradeConfirmPeerCta: "私も完了しました",
  tradeWaitingPeer: "相手の完了確認を待っています。",
  tradeDoneTitle: "取引が完了しました",
  tradeDoneHint: "DANでつながった取引です。",
  tradePeerClosed: "この取引はこれ以上進みません。",
  tradeClosedTitle: "取引が終了しました",
  tradeClosedSeekHint: "まだ探していますか？",
  tradeReopenCta: "もう一度探す",
  tradeReopenBody: "同じ条件で依頼を再開して相手を探します。",
  tradeReopenedToast: "同じ条件で再募集を始めました",
  tradeReopenedHint: "同じ条件で再び探しています。",
  activityMatchTradeClosed: "相手が取引を終了しました",
  matchStatusPotential: "条件一致",
  matchStatusInterested: "関心あり",
  matchStatusAccepted: "承認済み",
  matchStatusConnected: "接続済み",
  matchStatusDeclined: "お断り済み",
  matchStatusClosed: "終了",
  chatWith: "さんと会話",
  chatPlaceholder: "メッセージを入力",
  chatSend: "送信",
  chatEmpty: "まだメッセージはありません。場所や時間から合わせましょう。",
  loadingChat: "読み込み中…",
  // My DAN / nav
  navMy: "My DAN",
  navActivity: "お知らせ",
  navDemand: "探す",
  myDan: "My DAN",
  tabOverview: "一覧",
  tabDemands: "自分の依頼",
  tabOwned: "持ち物",
  tabSelling: "売却意向",
  tabMatches: "マッチ",
  tabResponses: "応じた依頼",
  noMatch: "まだマッチがありません",
  noMatchBody: "依頼を出すか返答するとここに表示されます。",
  matchReady: "条件が合う相手がいます",
  matchHint: "関心を送ると相手が接続を確認できます。",
  viewMatches: "マッチを見る",
  waitingSeller: "相手の返答待ち",
  connectedMsg: "つながりました。My DANで確認してください。",
  // Profile / activity
  profileTitle: "プロフィール",
  profileEdit: "プロフィール編集",
  profileBio: "紹介",
  profileJoined: "登録",
  profileCompleted: "取引完了",
  profileResponded: "返答・接続",
  profileRecent: "最近のDAN活動",
  profileRecentEmpty: "公開できる活動はまだありません。",
  profileArea: "主な活動エリア",
  profileSave: "保存",
  profileActivity: "活動",
  profileMyPosts: "自分の投稿",
  profileMyConnections: "つながり",
  activityTitle: "お知らせ",
  activityEmpty: "新しいお知らせはありません。",
  activityNewResponse: "新しい返答が届きました",
  activityAccepted: "返答が承認されました",
  activityDeclined: "返答がお断りされました",
  activityInterest: "購入の関心が届きました",
  activityConnected: "つながりました",
  activityMessage: "メッセージが届きました",
  activityClosed: "依頼が締め切りになりました",
  activityPeerConnected: "相手が接続を承認しました",
  activityExpiringSoon: "依頼の締め切りが近づいています",
  loadFailed: "読み込めませんでした。",
  dismiss: "閉じる",
  emptyHomeTitle: "まだ依頼がありません",
  emptyHomeBody: "最初の依頼を出すとここに表示されます。",
};
export function useDanCopy(): LocalizedCopy {
  const locale = useDanLocale();
  return useMemo(() => locale === "ja" ? { ...ko, ...jaPilotCopy } : ko, [locale]);
}
