import { writeFileSync } from "node:fs";

const ko = {
  brandTag: "찾는 사람이 먼저",
  navCreate: "요청 올리기",
  navFeed: "수요 보기",
  navMy: "My DAN",
  logout: "로그아웃",
  login: "로그인",
  navHome: "홈",
  navDemand: "수요",
  composerTitle: "뭐가 필요하세요?",
  composerPlaceholder:
    "사고 싶거나, 빌리거나, 누군가에게 부탁할 일을 적어보세요",
  composerHint: "필요한 사람이 먼저 올립니다.",
  typeBuy: "물건 구매",
  typeBorrow: "빌리기",
  typeTask: "심부름",
  typeService: "서비스",
  feedNowTitle: "지금 올라온 수요",
  feedNowDesc: "구매·대여·심부름·서비스가 함께 보입니다.",
  ctaCreate: "요청 올리기",
  ctaBrowse: "수요 둘러보기",
  featuredTitle: "지금 올라온 수요",
  featuredDesc: "필요한 사람이 먼저 남긴 요청입니다.",
  viewAllDemand: "전체 수요 보기",
  seekingSuffix: "명이 찾는 중",
  similarSeeking: "명이 비슷하게 찾는 중",
  priceHope: "희망 가격",
  recent7d: "최근 7일",
  highestIntent: "최고 희망가",
  viewDemand: "자세히",
  feedTitle: "수요 피드",
  feedDesc: "판매글이 아니라, 필요한 사람의 요청이 먼저입니다.",
  searchPh: "제목, 지역, 키워드",
  all: "전체",
  camera: "카메라",
  lens: "렌즈",
  electronics: "전자기기",
  furniture: "가구",
  camping: "캠핑",
  other: "기타",
  errand: "심부름",
  serviceCat: "서비스",
  rental: "대여",
  sealed: "미개봉",
  likeNew: "거의 새것",
  lightlyUsed: "사용감 적음",
  any: "상관없음",
  meetup: "직거래",
  shipping: "택배",
  won: "원",
  manWon: "만원",
  myung: "명",
  noChange: "변동 없음",
  seoul: "서울",
  gyeonggi: "경기",
  busan: "부산",
  daegu: "대구",
  incheon: "인천",
  mina: "민아",
  jun: "준호",
  hae: "해린",
  you: "나",
  seongdong: "서울 성동구",
  mapo: "서울 마포구",
  haeundae: "부산 해운대구",
  gangnam: "서울 강남구",
  pyeongtaek: "평택",
  next: "다음",
  prev: "이전",
  createTitle: "요청 올리기",
  createDesc: "유형만 고르면 필요한 입력만 보여요.",
  whatNeeded: "무엇이 필요하세요?",
  stepEssentials: "기본 정보",
  stepOptional: "선택 사항",
  optionalDetails: "나중에 수정해도 됩니다.",
  product: "제품",
  condition: "상태",
  maxPrice: "희망 가격 (최대)",
  maxPriceHint: "이 금액 이하라면 구매하고 싶어요.",
  location: "지역",
  tradeMethod: "거래 방식",
  submitDemand: "요청 등록",
  quotePrefix: "이하라면 구매하고 싶어요",
  titleLabel: "요청 제목",
  descLabel: "자세히",
  budgetLabel: "예산 / 보상",
  itemName: "물건",
  period: "기간",
  dueAt: "마감 / 희망 시간",
  reward: "보상",
  haveIt: "가지고 있어요",
  haveItTitle: "이 물건을 가지고 있나요?",
  haveItBody:
    "아직 팔 생각이 없어도 괜찮아요. 내 물건으로 등록하면 이 제품의 수요를 계속 확인할 수 있어요.",
  ownershipNote: "Ownership 은 판매글이 아닙니다.",
  registerOwned: "내 물건으로 등록",
  sellIntent: "판매 의향",
  sellCta: "이 가격이면 팔 수도 있어요",
  myDan: "My DAN",
  matchLead: "조건이 맞는 상대가 있어요.",
  sendInterest: "거래 의사 보내기",
  connect: "연결하기",
  noSearch: "검색 결과가 없어요",
  noSearchBody: "다른 키워드나 유형으로 찾아보세요.",
  seekingOnly: "찾는 중",
  highestHopeShort: "최고가",
  thisWeek: "이번 주",
  bandSuffix: "만원대",
  needLogin: "로그인이 필요해요",
  needLoginBody: "데모에서는 바로 로그인할 수 있어요.",
  demoLogin: "데모 로그인",
  matchStatusPotential: "조건 일치",
  matchStatusInterested: "관심 표시됨",
  matchStatusAccepted: "수락됨",
  matchStatusConnected: "연결됨",
  matchStatusDeclined: "거절됨",
  matchStatusClosed: "종료",
  buyUntil: "구매 희망",
  sellFrom: "판매 희망",
  untilSuffix: "까지",
  fromSuffix: "부터",
  waitingSeller: "상대 응답 대기",
  connectedMsg: "연결되었습니다. My DAN에서 확인하세요.",
  noMatch: "아직 매칭이 없어요",
  noMatchBody: "요청을 올리거나 응답하면 여기에 나타나요.",
  matchReady: "조건이 맞는 상대가 있어요",
  matchHint: "관심을 보내면 상대가 연결을 확인할 수 있어요.",
  viewMatches: "매칭 보기",
  newMatchesPrefix: "새 신호 ",
  newMatchesSuffix: "건",
  tabOverview: "한눈에",
  tabDemands: "내 요청",
  tabOwned: "내 물건",
  tabSelling: "판매 의향",
  tabMatches: "매칭",
  tabResponses: "내가 응답한 요청",
  statDemands: "내 요청",
  statOwned: "내 물건",
  statSelling: "판매 의향",
  statMatches: "매칭",
  myDescSuffix: " 님의 DAN 상태",
  resetDemo: "데모 초기화",
  missingProduct: "제품을 찾을 수 없어요",
  goBack: "돌아가기",
  missingOwn: "등록된 물건이 없어요",
  missingOwnBody: "먼저 내 물건을 등록해 주세요.",
  sellTitle: "판매 의향 남기기",
  sellPrompt: "이 가격이면 팔 수도 있어요.",
  sellNotListing: "판매글이 아니라 의향만 남깁니다.",
  currentHighest: "현재 최고 희망가",
  seekersLabel: "찾는 사람",
  iWould: "이 정도면",
  sellSentenceEnd: "에 팔 수 있어요",
  minPriceLabel: "최소 희망가",
  relatedMatchesMid: "관련 매칭 ",
  relatedMatchesEnd: "건이 있어요",
  buyerExists: "구매 희망자가 있어요",
  hopePrice: "희망가",
  sellConsiderPrice: "판매 희망가",
  ownTitle: "내 물건 등록",
  ownDesc: "팔지 않아도 수요를 볼 수 있어요.",
  ownDoneBody: "등록됐어요. 원하면 판매 의향을 남겨보세요.",
  ownAhaHigh: "최고 희망가",
  reviewDemand: "수요 다시 보기",
  locationPh: "예: 서울 성동구",
  seekingDetailSuffix: "명이 찾는 중",
  maxBudget: "최대",
  perDay: "/일",
  today: "오늘",
  respondCta: "제가 할게요",
  respondBorrow: "빌려드릴 수 있어요",
  respondService: "이 조건이면 가능합니다",
  respondSent: "응답을 보냈어요",
  acceptResponse: "연결하기",
  attentionTitle: "지금 확인할 것",
  myRequests: "내가 올린 요청",
  myResponses: "내가 응답한 요청",
  myConnections: "연결 / 매칭",
  myItems: "내가 가진 물건",
  signalMatch: "조건이 맞는 상대가 있어요",
  signalOwned: "내 물건을 찾는 사람이 있어요",
  signalResponse: "응답한 요청이 연결을 기다리고 있어요",
  emptyFeed: "아직 수요가 없어요",
  emptyFeedBody: "첫 요청을 올려보세요.",
  detailBudget: "예산",
  detailWhen: "시간",
  detailWhere: "장소",
  viewInMy: "내 DAN에서 보기",
  missingDemand: "요청을 찾을 수 없어요",
};

const lines = ["export const ko = {"];
for (const [key, value] of Object.entries(ko)) {
  lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
}
lines.push("} as const;");
lines.push("");
writeFileSync("src/copy/ko.ts", lines.join("\n"), "utf8");
console.log("wrote", Object.keys(ko).length, "keys");
